# LG Aimer 해커톤 실습

## Data load

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('./data/train.csv')

In [3]:
data.head()

,bant_submit,customer_country,business_unit,com_reg_ver_win_rate,customer_idx,customer_type,enterprise,historical_existing_cnt,id_strategic_ver,it_strategic_ver,...,response_corporate,expected_timeline,ver_cus,ver_pro,ver_win_rate_x,ver_win_ratio_per_bu,business_area,business_subarea,lead_owner,is_converted
0,1.0,/Quezon City/Philippines,AS,0.066667,32160,End-Customer,Enterprise,NaN,NaN,NaN,...,LGEPH,less than 3 months,1,0,0.003079,0.026846,corporate / office,Engineering,0,True
1,1.0,/PH-00/Philippines,AS,0.066667,23122,End-Customer,Enterprise,12.0,NaN,NaN,...,LGEPH,less than 3 months,1,0,0.003079,0.026846,corporate / office,Advertising,1,True
2,1.0,/Kolkata /India,AS,0.088889,1755,End-Customer,Enterprise,144.0,NaN,NaN,...,LGEIL,less than 3 months,1,0,0.003079,0.026846,corporate / office,Construction,2,True
3,1.0,/Bhubaneswar/India,AS,0.088889,4919,End-Customer,Enterprise,NaN,NaN,NaN,...,LGEIL,less than 3 months,1,0,0.003079,0.026846,corporate / office,IT/Software,3,True
4,1.0,/Hyderabad/India,AS,0.088889,17126,Specifier/ Influencer,Enterprise,NaN,NaN,NaN,...,LGEIL,less than 3 months,0,0,0.003079,0.026846,corporate / office,NaN,4,True

In [5]:
data.describe

<bound method NDFrame.describe of        bant_submit          customer_country business_unit  \
0             1.00  /Quezon City/Philippines            AS
1             1.00        /PH-00/Philippines            AS
2             1.00           /Kolkata /India            AS
3             1.00        /Bhubaneswar/India            AS
4             1.00          /Hyderabad/India            AS
...            ...                       ...           ...
59294         1.00           /Sląskie/Poland            AS
59295         0.75      /Bogotá DC /Colombia            AS
59296         0.75               /Pisco/Peru            AS
59297         1.00  /santa cruz bolivia/Peru            AS
59298         0.75             /paris/France      Solution

       com_reg_ver_win_rate  customer_idx          customer_type  enterprise  \
0                  0.066667         32160           End-Customer  Enterprise
1                  0.066667         23122           End-Customer  Enterprise
2                  0.088889          1755           End-Customer  Enterprise
3                  0.088889          4919           End-Customer  Enterprise
4                  0.088889         17126  Specifier/ Influencer  Enterprise
...                     ...           ...                    ...         ...
59294                   NaN         33747           End Customer         SMB
59295              0.040000         35420  Specifier/ Influencer  Enterprise
59296              0.040000         19249  Specifier/ Influencer  Enterprise
59297              0.040000         40327                    NaN  Enterprise
59298                   NaN         30268                    NaN  Enterprise

       historical_existing_cnt  id_strategic_ver  it_strategic_ver  ...  \
0                          NaN               NaN               NaN  ...
1                         12.0               NaN               NaN  ...
2                        144.0               NaN               NaN  ...
3                          NaN               NaN               NaN  ...
4                          NaN               NaN               NaN  ...
...                        ...               ...               ...  ...
59294                      NaN               NaN               NaN  ...
59295                      NaN               NaN               NaN  ...
59296                      NaN               NaN               NaN  ...
59297                      NaN               NaN               NaN  ...
59298                      NaN               NaN               NaN  ...

       response_corporate    expected_timeline  ver_cus ver_pro  \
0                   LGEPH   less than 3 months        1       0
1                   LGEPH   less than 3 months        1       0
2                   LGEIL   less than 3 months        1       0
3                   LGEIL   less than 3 months        1       0
4                   LGEIL   less than 3 months        0       0
...                   ...                  ...      ...     ...
59294               LGEPL  3 months ~ 6 months        0       0
59295               LGECB    9 months ~ 1 year        0       0
59296               LGEPR   less than 3 months        0       0
59297               LGEPR     more than a year        0       0
59298               LGEKR   less than 3 months        0       0

      ver_win_rate_x ver_win_ratio_per_bu       business_area  \
0           0.003079             0.026846  corporate / office
1           0.003079             0.026846  corporate / office
2           0.003079             0.026846  corporate / office
3           0.003079             0.026846  corporate / office
4           0.003079             0.026846  corporate / office
...              ...                  ...                 ...
59294       0.000026             0.028777     public facility
59295       0.000026             0.028777     public facility
59296       0.000026             0.028777     public facility
59297       0.000026             0.028777     public facility
59298       0.000026                  NaN     public facility

      business_subarea lead_owner is_converted
0          Engineering          0         True
1          Advertising          1         True
2         Construction          2         True
3          IT/Software          3         True
4                  NaN          4         True
...                ...        ...          ...
59294           Others        694        False
59295              NaN         39        False
59296              NaN        125        False
59297              NaN        134        False
59298              NaN        441        False

[59299 rows x 29 columns]>