# 데이터를 사용하기 좋게 미리 일정 부분 조정 및 새로운 데이터 생성

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Bundesliga 선수 데이터 확인

In [2]:
BL_Player_df = pd.read_csv('./Budesliga_data/Bundesliga_Player_22_23.csv')

In [3]:
BL_Player_df.shape

(286, 35)

In [4]:
# 필요없는 컬럼 삭제

BL_Player_df.drop('Unnamed: 0', axis=1, inplace=True)
BL_Player_df.head()

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Disp,UnsTch,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG
0,Jude Bellingham,44,Borussia Dortmund,19,M(CLR),30(1),2693,4,1.1,51.2,...,1.9,2.0,2.5,1.1,1.3,0.0,0.9,0.5,0.1,0
1,Joshua Kimmich,37,Bayern,28,"D(CR),DMC,M(R)",32(1),2815,6,2.6,75.5,...,0.8,0.8,2.4,1.2,0.7,0.0,1.1,1.0,0.2,0
2,Niclas Füllkrug,42,Werder Bremen,30,FW,28,2479,5,1.2,32.3,...,1.8,2.6,0.3,0.0,1.2,0.0,0.9,0.4,0.1,0
3,Christopher Nkunku,7614,RBL,25,"M(CLR),FW",20(5),1899,4,1.6,23.8,...,1.5,1.8,0.2,0.3,0.7,0.0,0.4,0.2,0.1,0
4,Jamal Musiala,37,Bayern,20,M(CL),26(7),2212,10,1.6,30.0,...,2.1,2.4,1.0,0.6,0.7,0.0,0.1,0.7,0.1,0

In [5]:
BL_Player_df.columns = ['player_name', 'team_number', 'Team', 'age', 'position', 'Apps',
       'Mins', 'Assists', 'KeyP', 'AvgP', 'PS%', 'Crosses', 'LongB', 'ThrB',
       'Rating', 'Goals', 'Yel', 'Red', 'SpG', 'AerialsWon', 'MoM', 'Dribble',
       'Fouled', 'Off', 'Disp', 'UnsTch', 'Tackles', 'Inter', 'Fouls',
       'Offsides', 'Clear', 'Drb', 'Blocks', 'OwnG']

In [6]:
# 결측치 유무 확인

BL_Player_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 34 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   player_name  286 non-null    object
 1   team_number  286 non-null    int64
 2   Team         286 non-null    object
 3   age          286 non-null    int64
 4   position     286 non-null    object
 5   Apps         286 non-null    object
 6   Mins         286 non-null    int64
 7   Assists      286 non-null    int64
 8   KeyP         286 non-null    float64
 9   AvgP         286 non-null    float64
 10  PS%          286 non-null    float64
 11  Crosses      286 non-null    float64
 12  LongB        286 non-null    float64
 13  ThrB         286 non-null    float64
 14  Rating       286 non-null    float64
 15  Goals        286 non-null    int64
 16  Yel          286 non-null    int64
 17  Red          286 non-null    int64
 18  SpG          286 non-null    float64
 19  AerialsWon   286 non-null    float64
 20  MoM          286 non-null    int64
 21  Dribble      286 non-null    float64
 22  Fouled       286 non-null    float64
 23  Off          286 non-null    float64
 24  Disp         286 non-null    float64
 25  UnsTch       286 non-null    float64
 26  Tackles      286 non-null    float64
 27  Inter        286 non-null    float64
 28  Fouls        286 non-null    float64
 29  Offsides     286 non-null    float64
 30  Clear        286 non-null    float64
 31  Drb          286 non-null    float64
 32  Blocks       286 non-null    float64
 33  OwnG         286 non-null    int64
dtypes: float64(21), int64(9), object(4)
memory usage: 76.1+ KB

## 포지션 전처리

In [7]:
BL_Player_df['position'].unique()

array([' M(CLR)  ', ' D(CR),DMC,M(R)  ', ' FW  ', ' M(CLR),FW  ',
       ' M(CL)  ', ' AM(CLR)  ', ' AM(R),FW  ', ' D(L),M(CL)  ',
       ' AM(CL)  ', ' D(R),M(CLR)  ', ' AM(LR),FW  ', ' M(LR),FW  ',
       ' D(CLR),M(R)  ', ' D(L),M(LR)  ', ' D(C)  ', ' D(R),M(R)  ',
       ' AM(CR),FW  ', ' AM(CLR),FW  ', ' AM(L),FW  ', ' DMC  ',
       ' M(CR)  ', ' GK  ', ' D(L),M(L)  ', ' D(CR)  ', ' AM(C),FW  ',
       ' D(CL),DMC,M(L)  ', ' D(CR),DMC  ', ' D(CLR),DMC  ', ' M(C)  ',
       ' D(LR)  ', ' D(R),M(CR)  ', ' D(CR),M(R)  ', ' D(C),DMC  ',
       ' D(LR),DMC,M(LR)  ', ' D(R),M(CLR),FW  ', ' M(LR)  ', ' D(CL)  ',
       ' D(CLR),M(L)  ', ' D(CLR)  ', ' D(CL),M(L)  ', ' AM(C)  ',
       ' D(C),M(CR)  ', ' D(LR),M(R)  ', ' D(LR),DMC,M(L)  ',
       ' D(R),M(C)  ', ' AM(CL),FW  ', ' D(C),M(C)  ', ' D(R),M(LR)  ',
       ' D(CR),M(C)  ', ' D(R),DMC  ', ' D(CR),M(CR)  ', ' M(L)  ',
       ' Forward  ', ' Midfielder  ', ' D(R),M(R),FW  ', ' AM(CR)  ',
       ' AM(R)  '], dtype=object)

In [8]:
# 전체 데이터에서 position 데이터만 추출

position_df = BL_Player_df[['position']]
position_df

              position
0             M(CLR)
1     D(CR),DMC,M(R)
2                 FW
3          M(CLR),FW
4              M(CL)
..                 ...
281               FW
282               FW
283             M(C)
284               FW
285         M(LR),FW

[286 rows x 1 columns]

In [9]:
# 리스트 형태로 변환

tmp_li = position_df['position'].tolist()
tmp_li

[' M(CLR)  ',
 ' D(CR),DMC,M(R)  ',
 ' FW  ',
 ' M(CLR),FW  ',
 ' M(CL)  ',
 ' AM(CLR)  ',
 ' AM(R),FW  ',
 ' M(CLR),FW  ',
 ' D(L),M(CL)  ',
 ' AM(CL)  ',
 ' D(R),M(CLR)  ',
 ' FW  ',
 ' AM(LR),FW  ',
 ' M(LR),FW  ',
 ' M(CLR),FW  ',
 ' D(CLR),M(R)  ',
 ' D(L),M(LR)  ',
 ' M(CLR),FW  ',
 ' D(C)  ',
 ' D(R),M(R)  ',
 ' AM(CR),FW  ',
 ' AM(CLR),FW  ',
 ' AM(L),FW  ',
 ' M(CLR),FW  ',
 ' D(C)  ',
 ' AM(CLR)  ',
 ' M(CLR),FW  ',
 ' D(C)  ',
 ' DMC  ',
 ' M(CR)  ',
 ' GK  ',
 ' D(L),M(L)  ',
 ' FW  ',
 ' D(CR)  ',
 ' D(L),M(L)  ',
 ' AM(C),FW  ',
 ' AM(R),FW  ',
 ' D(L),M(CL)  ',
 ' D(C)  ',
 ' D(C)  ',
 ' DMC  ',
 ' D(CL),DMC,M(L)  ',
 ' D(CR),DMC  ',
 ' D(R),M(R)  ',
 ' D(C)  ',
 ' AM(CLR),FW  ',
 ' AM(CLR),FW  ',
 ' AM(CLR),FW  ',
 ' M(CR)  ',
 ' AM(CLR),FW  ',
 ' D(C)  ',
 ' M(CR)  ',
 ' D(CLR),DMC  ',
 ' DMC  ',
 ' D(C)  ',
 ' M(C)  ',
 ' D(C)  ',
 ' D(LR)  ',
 ' D(R),M(CR)  ',
 ' M(C)  ',
 ' AM(LR),FW  ',
 ' AM(CLR),FW  ',
 ' M(C)  ',
 ' AM(CLR),FW  ',
 ' AM(CLR),FW  ',
 ' M(CL)  ',
 ' FW  ',
 ' M(CLR),FW  ',
 ' AM(CLR),FW  ',
 ' AM(CLR),FW  ',
 ' M(C)  ',
 ' D(R),M(CLR)  ',
 ' D(R),M(R)  ',
 ' DMC  ',
 ' D(C)  ',
 ' D(CR),M(R)  ',
 ' M(CLR),FW  ',
 ' AM(CLR),FW  ',
 ' GK  ',
 ' GK  ',
 ' D(CR)  ',
 ' D(C),DMC  ',
 ' GK  ',
 ' AM(CLR),FW  ',
 ' GK  ',
 ' D(CR),M(R)  ',
 ' AM(L),FW  ',
 ' D(LR),DMC,M(LR)  ',
 ' AM(L),FW  ',
 ' D(CR)  ',
 ' D(C),DMC  ',
 ' DMC  ',
 ' D(R),M(CR)  ',
 ' D(L),M(L)  ',
 ' D(R),M(CLR),FW  ',
 ' D(C)  ',
 ' D(C)  ',
 ' M(CR)  ',
 ' D(C)  ',
 ' M(LR)  ',
 ' M(CLR),FW  ',
 ' D(CR),M(R)  ',
 ' GK  ',
 ' D(C),DMC  ',
 ' M(C)  ',
 ' M(C)  ',
 ' D(CL)  ',
 ' D(CLR),M(L)  ',
 ' AM(CLR),FW  ',
 ' AM(C),FW  ',
 ' M(CLR),FW  ',
 ' D(CLR)  ',
 ' DMC  ',
 ' D(C)  ',
 ' M(CR)  ',
 ' AM(C),FW  ',
 ' D(CL)  ',
 ' D(CL)  ',
 ' D(CL),M(L)  ',
 ' AM(CR),FW  ',
 ' D(L),M(L)  ',
 ' D(CL),M(L)  ',
 ' DMC  ',
 ' D(CL)  ',
 ' M(CLR)  ',
 ' D(C)  ',
 ' D(L),M(L)  ',
 ' D(C),DMC  ',
 ' M(CLR),FW  ',
 ' GK  ',
 ' M(CLR),FW  ',
 ' D(L),M(L)  ',
 ' AM(CLR),FW  ',
 ' D(CR)  ',
 ' M(CLR),FW  ',
 ' D(C)  ',
 ' M(CLR),FW  ',
 ' M(CLR),FW  ',
 ' D(L),M(LR)  ',
 ' D(CR)  ',
 ' M(CLR)  ',
 ' FW  ',
 ' GK  ',
 ' GK  ',
 ' AM(C)  ',
 ' DMC  ',
 ' D(C)  ',
 ' D(L),M(CL)  ',
 ' M(CLR),FW  ',
 ' GK  ',
 ' M(C)  ',
 ' M(C)  ',
 ' D(C),M(CR)  ',
 ' D(C),DMC  ',
 ' FW  ',
 ' AM(CLR)  ',
 ' D(C)  ',
 ' M(CLR),FW  ',
 ' AM(CLR),FW  ',
 ' FW  ',
 ' D(C),DMC  ',
 ' D(C)  ',
 ' D(C)  ',
 ' M(C)  ',
 ' AM(CLR)  ',
 ' AM(CLR),FW  ',
 ' D(C)  ',
 ' D(C),DMC  ',
 ' AM(CLR),FW  ',
 ' FW  ',
 ' D(L),M(LR)  ',
 ' D(CR),DMC  ',
 ' D(CL),M(L)  ',
 ' FW  ',
 ' D(LR),M(R)  ',
 ' M(CR)  ',
 ' D(L),M(L)  ',
 ' D(C),DMC  ',
 ' AM(C),FW  ',
 ' D(C)  ',
 ' GK  ',
 ' AM(CLR),FW  ',
 ' D(CR)  ',
 ' D(LR),DMC,M(L)  ',
 ' D(R),M(C)  ',
 ' D(CR),M(R)  ',
 ' AM(L),FW  ',
 ' M(LR)  ',
 ' D(C),DMC  ',
 ' D(C),DMC  ',
 ' D(CR),DMC  ',
 ' D(CL),M(L)  ',
 ' D(CL),M(L)  ',
 ' AM(CL),FW  ',
 ' D(CR)  ',
 ' AM(CLR),FW  ',
 ' FW  ',
 ' M(C)  ',
 ' M(C)  ',
 ' M(CLR),FW  ',
 ' D(C),M(C)  ',
 ' M(C)  ',
 ' M(C)  ',
 ' AM(CLR),FW  ',
 ' D(R),M(R)  ',
 ' M(CLR)  ',
 ' D(R),M(LR)  ',
 ' D(CLR)  ',
 ' M(CR)  ',
 ' D(L),M(L)  ',
 ' D(LR),M(R)  ',
 ' M(C)  ',
 ' FW  ',
 ' AM(C),FW  ',
 ' GK  ',
 ' D(CR),M(R)  ',
 ' D(CR),M(C)  ',
 ' D(CLR)  ',
 ' FW  ',
 ' AM(C)  ',
 ' AM(CLR),FW  ',
 ' D(L),M(L)  ',
 ' M(CLR)  ',
 ' AM(CR),FW  ',
 ' AM(R),FW  ',
 ' D(L),M(CL)  ',
 ' AM(CLR)  ',
 ' D(C)  ',
 ' D(R),DMC  ',
 ' D(L),M(CL)  ',
 ' M(CLR)  ',
 ' M(C)  ',
 ' D(CR)  ',
 ' GK  ',
 ' D(R),M(R)  ',
 ' D(C)  ',
 ' D(CR),M(CR)  ',
 ' D(L),M(L)  ',
 ' D(CL)  ',
 ' M(L)  ',
 ' DMC  ',
 ' DMC  ',
 ' D(CLR)  ',
 ' GK  ',
 ' AM(CL),FW  ',
 ' Forward  ',
 ' D(L),M(L)  ',
 ' GK  ',
 ' AM(R),FW  ',
 ' D(R),M(R)  ',
 ' D(R),M(CR)  ',
 ' D(L),M(LR)  ',
 ' AM(CLR),FW  ',
 ' GK  ',
 ' D(C)  ',
 ' FW  ',
 ' AM(CL),FW  ',
 ' AM(CL),FW  ',
 ' DMC  ',
 ' Midfielder  ',
 ' DMC  ',
 ' D(L),M(L)  ',
 ' AM(C)  ',
 ' DMC  ',
 ' D(R),M(R),FW  ',
 ' AM(C),FW  ',
 ' DMC  ',
 ' AM(L),FW  ',
 ' AM(CR)  ',
 ' M(CLR)  ',
 ' D(R),M(LR)  ',
 ' AM(CLR),FW  ',
 ' M(CLR)  ',
 ' D(C)  ',
 ' DMC  ',
 ' AM(LR),FW  ',
 ' AM(R)  ',
 ' GK  ',
 ' AM(CLR),FW  ',
 ' D(R),M(R)  ',
 ' AM(CR),FW  ',
 ' FW  ',
 ' FW  ',
 ' M(C)  ',
 ' FW  ',
 ' M(LR),FW  ']

In [10]:
# 포지션이 여러 개인 경우 하나의 포지션만 남긴다.

for i in range(len(tmp_li)):
    tmp = tmp_li[i]
    if ',' in tmp:
        tmp_li[i] = tmp.split(',')[0]

In [11]:
tmp = pd.DataFrame(tmp_li)
tmp.columns = ['position']
tmp

      position
0     M(CLR)
1        D(CR)
2         FW
3       M(CLR)
4      M(CL)
..         ...
281       FW
282       FW
283     M(C)
284       FW
285      M(LR)

[286 rows x 1 columns]

In [12]:
# 전체 데이터에 새로운 포지션 값 적용

BL_Player_df['position'] = tmp['position']
BL_Player_df['position'] # 변경이 되었는지 확인

0       M(CLR)
1          D(CR)
2           FW
3         M(CLR)
4        M(CL)
         ...
281         FW
282         FW
283       M(C)
284         FW
285        M(LR)
Name: position, Length: 286, dtype: object

In [13]:
# unique값 확인
# 공백이 있는 경우 같은 포지션도 다르게 판단 -> 공백을 지워준다.

tmp_li = BL_Player_df['position'].tolist()
tmp_li

[' M(CLR)  ',
 ' D(CR)',
 ' FW  ',
 ' M(CLR)',
 ' M(CL)  ',
 ' AM(CLR)  ',
 ' AM(R)',
 ' M(CLR)',
 ' D(L)',
 ' AM(CL)  ',
 ' D(R)',
 ' FW  ',
 ' AM(LR)',
 ' M(LR)',
 ' M(CLR)',
 ' D(CLR)',
 ' D(L)',
 ' M(CLR)',
 ' D(C)  ',
 ' D(R)',
 ' AM(CR)',
 ' AM(CLR)',
 ' AM(L)',
 ' M(CLR)',
 ' D(C)  ',
 ' AM(CLR)  ',
 ' M(CLR)',
 ' D(C)  ',
 ' DMC  ',
 ' M(CR)  ',
 ' GK  ',
 ' D(L)',
 ' FW  ',
 ' D(CR)  ',
 ' D(L)',
 ' AM(C)',
 ' AM(R)',
 ' D(L)',
 ' D(C)  ',
 ' D(C)  ',
 ' DMC  ',
 ' D(CL)',
 ' D(CR)',
 ' D(R)',
 ' D(C)  ',
 ' AM(CLR)',
 ' AM(CLR)',
 ' AM(CLR)',
 ' M(CR)  ',
 ' AM(CLR)',
 ' D(C)  ',
 ' M(CR)  ',
 ' D(CLR)',
 ' DMC  ',
 ' D(C)  ',
 ' M(C)  ',
 ' D(C)  ',
 ' D(LR)  ',
 ' D(R)',
 ' M(C)  ',
 ' AM(LR)',
 ' AM(CLR)',
 ' M(C)  ',
 ' AM(CLR)',
 ' AM(CLR)',
 ' M(CL)  ',
 ' FW  ',
 ' M(CLR)',
 ' AM(CLR)',
 ' AM(CLR)',
 ' M(C)  ',
 ' D(R)',
 ' D(R)',
 ' DMC  ',
 ' D(C)  ',
 ' D(CR)',
 ' M(CLR)',
 ' AM(CLR)',
 ' GK  ',
 ' GK  ',
 ' D(CR)  ',
 ' D(C)',
 ' GK  ',
 ' AM(CLR)',
 ' GK  ',
 ' D(CR)',
 ' AM(L)',
 ' D(LR)',
 ' AM(L)',
 ' D(CR)  ',
 ' D(C)',
 ' DMC  ',
 ' D(R)',
 ' D(L)',
 ' D(R)',
 ' D(C)  ',
 ' D(C)  ',
 ' M(CR)  ',
 ' D(C)  ',
 ' M(LR)  ',
 ' M(CLR)',
 ' D(CR)',
 ' GK  ',
 ' D(C)',
 ' M(C)  ',
 ' M(C)  ',
 ' D(CL)  ',
 ' D(CLR)',
 ' AM(CLR)',
 ' AM(C)',
 ' M(CLR)',
 ' D(CLR)  ',
 ' DMC  ',
 ' D(C)  ',
 ' M(CR)  ',
 ' AM(C)',
 ' D(CL)  ',
 ' D(CL)  ',
 ' D(CL)',
 ' AM(CR)',
 ' D(L)',
 ' D(CL)',
 ' DMC  ',
 ' D(CL)  ',
 ' M(CLR)  ',
 ' D(C)  ',
 ' D(L)',
 ' D(C)',
 ' M(CLR)',
 ' GK  ',
 ' M(CLR)',
 ' D(L)',
 ' AM(CLR)',
 ' D(CR)  ',
 ' M(CLR)',
 ' D(C)  ',
 ' M(CLR)',
 ' M(CLR)',
 ' D(L)',
 ' D(CR)  ',
 ' M(CLR)  ',
 ' FW  ',
 ' GK  ',
 ' GK  ',
 ' AM(C)  ',
 ' DMC  ',
 ' D(C)  ',
 ' D(L)',
 ' M(CLR)',
 ' GK  ',
 ' M(C)  ',
 ' M(C)  ',
 ' D(C)',
 ' D(C)',
 ' FW  ',
 ' AM(CLR)  ',
 ' D(C)  ',
 ' M(CLR)',
 ' AM(CLR)',
 ' FW  ',
 ' D(C)',
 ' D(C)  ',
 ' D(C)  ',
 ' M(C)  ',
 ' AM(CLR)  ',
 ' AM(CLR)',
 ' D(C)  ',
 ' D(C)',
 ' AM(CLR)',
 ' FW  ',
 ' D(L)',
 ' D(CR)',
 ' D(CL)',
 ' FW  ',
 ' D(LR)',
 ' M(CR)  ',
 ' D(L)',
 ' D(C)',
 ' AM(C)',
 ' D(C)  ',
 ' GK  ',
 ' AM(CLR)',
 ' D(CR)  ',
 ' D(LR)',
 ' D(R)',
 ' D(CR)',
 ' AM(L)',
 ' M(LR)  ',
 ' D(C)',
 ' D(C)',
 ' D(CR)',
 ' D(CL)',
 ' D(CL)',
 ' AM(CL)',
 ' D(CR)  ',
 ' AM(CLR)',
 ' FW  ',
 ' M(C)  ',
 ' M(C)  ',
 ' M(CLR)',
 ' D(C)',
 ' M(C)  ',
 ' M(C)  ',
 ' AM(CLR)',
 ' D(R)',
 ' M(CLR)  ',
 ' D(R)',
 ' D(CLR)  ',
 ' M(CR)  ',
 ' D(L)',
 ' D(LR)',
 ' M(C)  ',
 ' FW  ',
 ' AM(C)',
 ' GK  ',
 ' D(CR)',
 ' D(CR)',
 ' D(CLR)  ',
 ' FW  ',
 ' AM(C)  ',
 ' AM(CLR)',
 ' D(L)',
 ' M(CLR)  ',
 ' AM(CR)',
 ' AM(R)',
 ' D(L)',
 ' AM(CLR)  ',
 ' D(C)  ',
 ' D(R)',
 ' D(L)',
 ' M(CLR)  ',
 ' M(C)  ',
 ' D(CR)  ',
 ' GK  ',
 ' D(R)',
 ' D(C)  ',
 ' D(CR)',
 ' D(L)',
 ' D(CL)  ',
 ' M(L)  ',
 ' DMC  ',
 ' DMC  ',
 ' D(CLR)  ',
 ' GK  ',
 ' AM(CL)',
 ' Forward  ',
 ' D(L)',
 ' GK  ',
 ' AM(R)',
 ' D(R)',
 ' D(R)',
 ' D(L)',
 ' AM(CLR)',
 ' GK  ',
 ' D(C)  ',
 ' FW  ',
 ' AM(CL)',
 ' AM(CL)',
 ' DMC  ',
 ' Midfielder  ',
 ' DMC  ',
 ' D(L)',
 ' AM(C)  ',
 ' DMC  ',
 ' D(R)',
 ' AM(C)',
 ' DMC  ',
 ' AM(L)',
 ' AM(CR)  ',
 ' M(CLR)  ',
 ' D(R)',
 ' AM(CLR)',
 ' M(CLR)  ',
 ' D(C)  ',
 ' DMC  ',
 ' AM(LR)',
 ' AM(R)  ',
 ' GK  ',
 ' AM(CLR)',
 ' D(R)',
 ' AM(CR)',
 ' FW  ',
 ' FW  ',
 ' M(C)  ',
 ' FW  ',
 ' M(LR)']

In [14]:
# 공백 삭제

for i in range(len(tmp_li)):
    tmp_li[i] = tmp_li[i].replace(' ', '')
tmp_li

['M(CLR)',
 'D(CR)',
 'FW',
 'M(CLR)',
 'M(CL)',
 'AM(CLR)',
 'AM(R)',
 'M(CLR)',
 'D(L)',
 'AM(CL)',
 'D(R)',
 'FW',
 'AM(LR)',
 'M(LR)',
 'M(CLR)',
 'D(CLR)',
 'D(L)',
 'M(CLR)',
 'D(C)',
 'D(R)',
 'AM(CR)',
 'AM(CLR)',
 'AM(L)',
 'M(CLR)',
 'D(C)',
 'AM(CLR)',
 'M(CLR)',
 'D(C)',
 'DMC',
 'M(CR)',
 'GK',
 'D(L)',
 'FW',
 'D(CR)',
 'D(L)',
 'AM(C)',
 'AM(R)',
 'D(L)',
 'D(C)',
 'D(C)',
 'DMC',
 'D(CL)',
 'D(CR)',
 'D(R)',
 'D(C)',
 'AM(CLR)',
 'AM(CLR)',
 'AM(CLR)',
 'M(CR)',
 'AM(CLR)',
 'D(C)',
 'M(CR)',
 'D(CLR)',
 'DMC',
 'D(C)',
 'M(C)',
 'D(C)',
 'D(LR)',
 'D(R)',
 'M(C)',
 'AM(LR)',
 'AM(CLR)',
 'M(C)',
 'AM(CLR)',
 'AM(CLR)',
 'M(CL)',
 'FW',
 'M(CLR)',
 'AM(CLR)',
 'AM(CLR)',
 'M(C)',
 'D(R)',
 'D(R)',
 'DMC',
 'D(C)',
 'D(CR)',
 'M(CLR)',
 'AM(CLR)',
 'GK',
 'GK',
 'D(CR)',
 'D(C)',
 'GK',
 'AM(CLR)',
 'GK',
 'D(CR)',
 'AM(L)',
 'D(LR)',
 'AM(L)',
 'D(CR)',
 'D(C)',
 'DMC',
 'D(R)',
 'D(L)',
 'D(R)',
 'D(C)',
 'D(C)',
 'M(CR)',
 'D(C)',
 'M(LR)',
 'M(CLR)',
 'D(CR)',
 'GK',
 'D(C)',
 'M(C)',
 'M(C)',
 'D(CL)',
 'D(CLR)',
 'AM(CLR)',
 'AM(C)',
 'M(CLR)',
 'D(CLR)',
 'DMC',
 'D(C)',
 'M(CR)',
 'AM(C)',
 'D(CL)',
 'D(CL)',
 'D(CL)',
 'AM(CR)',
 'D(L)',
 'D(CL)',
 'DMC',
 'D(CL)',
 'M(CLR)',
 'D(C)',
 'D(L)',
 'D(C)',
 'M(CLR)',
 'GK',
 'M(CLR)',
 'D(L)',
 'AM(CLR)',
 'D(CR)',
 'M(CLR)',
 'D(C)',
 'M(CLR)',
 'M(CLR)',
 'D(L)',
 'D(CR)',
 'M(CLR)',
 'FW',
 'GK',
 'GK',
 'AM(C)',
 'DMC',
 'D(C)',
 'D(L)',
 'M(CLR)',
 'GK',
 'M(C)',
 'M(C)',
 'D(C)',
 'D(C)',
 'FW',
 'AM(CLR)',
 'D(C)',
 'M(CLR)',
 'AM(CLR)',
 'FW',
 'D(C)',
 'D(C)',
 'D(C)',
 'M(C)',
 'AM(CLR)',
 'AM(CLR)',
 'D(C)',
 'D(C)',
 'AM(CLR)',
 'FW',
 'D(L)',
 'D(CR)',
 'D(CL)',
 'FW',
 'D(LR)',
 'M(CR)',
 'D(L)',
 'D(C)',
 'AM(C)',
 'D(C)',
 'GK',
 'AM(CLR)',
 'D(CR)',
 'D(LR)',
 'D(R)',
 'D(CR)',
 'AM(L)',
 'M(LR)',
 'D(C)',
 'D(C)',
 'D(CR)',
 'D(CL)',
 'D(CL)',
 'AM(CL)',
 'D(CR)',
 'AM(CLR)',
 'FW',
 'M(C)',
 'M(C)',
 'M(CLR)',
 'D(C)',
 'M(C)',
 'M(C)',
 'AM(CLR)',
 'D(R)',
 'M(CLR)',
 'D(R)',
 'D(CLR)',
 'M(CR)',
 'D(L)',
 'D(LR)',
 'M(C)',
 'FW',
 'AM(C)',
 'GK',
 'D(CR)',
 'D(CR)',
 'D(CLR)',
 'FW',
 'AM(C)',
 'AM(CLR)',
 'D(L)',
 'M(CLR)',
 'AM(CR)',
 'AM(R)',
 'D(L)',
 'AM(CLR)',
 'D(C)',
 'D(R)',
 'D(L)',
 'M(CLR)',
 'M(C)',
 'D(CR)',
 'GK',
 'D(R)',
 'D(C)',
 'D(CR)',
 'D(L)',
 'D(CL)',
 'M(L)',
 'DMC',
 'DMC',
 'D(CLR)',
 'GK',
 'AM(CL)',
 'Forward',
 'D(L)',
 'GK',
 'AM(R)',
 'D(R)',
 'D(R)',
 'D(L)',
 'AM(CLR)',
 'GK',
 'D(C)',
 'FW',
 'AM(CL)',
 'AM(CL)',
 'DMC',
 'Midfielder',
 'DMC',
 'D(L)',
 'AM(C)',
 'DMC',
 'D(R)',
 'AM(C)',
 'DMC',
 'AM(L)',
 'AM(CR)',
 'M(CLR)',
 'D(R)',
 'AM(CLR)',
 'M(CLR)',
 'D(C)',
 'DMC',
 'AM(LR)',
 'AM(R)',
 'GK',
 'AM(CLR)',
 'D(R)',
 'AM(CR)',
 'FW',
 'FW',
 'M(C)',
 'FW',
 'M(LR)']

In [15]:
tmp = pd.DataFrame(tmp_li, columns=['position'])
tmp

    position
0     M(CLR)
1      D(CR)
2         FW
3     M(CLR)
4      M(CL)
..       ...
281       FW
282       FW
283     M(C)
284       FW
285    M(LR)

[286 rows x 1 columns]

In [16]:
# 원래 데이터에 적용

BL_Player_df['position'] = tmp

In [17]:
# 각 포지션이 잘 적용되었는지 확인

BL_Player_df['position'].unique()

array(['M(CLR)', 'D(CR)', 'FW', 'M(CL)', 'AM(CLR)', 'AM(R)', 'D(L)',
       'AM(CL)', 'D(R)', 'AM(LR)', 'M(LR)', 'D(CLR)', 'D(C)', 'AM(CR)',
       'AM(L)', 'DMC', 'M(CR)', 'GK', 'AM(C)', 'D(CL)', 'M(C)', 'D(LR)',
       'M(L)', 'Forward', 'Midfielder'], dtype=object)

## Apps 전처리

In [18]:
# Apps -> 출전횟수
# 교체 출전의 경우 괄호에 있다.
# 그냥 합쳐준다.
apps_df = BL_Player_df['Apps']
apps_df.head()

0    30(1)
1    32(1)
2       28
3    20(5)
4    26(7)
Name: Apps, dtype: object

In [19]:
tmp_li = apps_df.tolist()
tmp_li

['30(1)',
 '32(1)',
 '28',
 '20(5)',
 '26(7)',
 '28(3)',
 '31(1)',
 '29(3)',
 '26(1)',
 '30(3)',
 '30(1)',
 '15(4)',
 '22(4)',
 '16(8)',
 '14(5)',
 '27(3)',
 '24(2)',
 '21(6)',
 '21',
 '32(2)',
 '27(3)',
 '22(12)',
 '28(2)',
 '20(12)',
 '27(1)',
 '31(1)',
 '33',
 '33',
 '32',
 '32',
 '29',
 '22(3)',
 '31(3)',
 '26(2)',
 '25',
 '34',
 '23(3)',
 '32',
 '25',
 '24(6)',
 '33',
 '28',
 '34',
 '29(1)',
 '27(4)',
 '15(8)',
 '33',
 '33(1)',
 '15(7)',
 '30(3)',
 '28(1)',
 '22(5)',
 '20(7)',
 '33',
 '32',
 '28(1)',
 '31',
 '11(8)',
 '17(4)',
 '19(11)',
 '20(4)',
 '18(7)',
 '22(8)',
 '27(5)',
 '16(10)',
 '29(3)',
 '17(16)',
 '17(2)',
 '28(3)',
 '23(4)',
 '19(6)',
 '17(8)',
 '15(3)',
 '30',
 '27(2)',
 '19(3)',
 '20(9)',
 '25(7)',
 '23',
 '34',
 '23(6)',
 '32',
 '27',
 '24(10)',
 '34',
 '20(5)',
 '20(2)',
 '23(7)',
 '30',
 '26(4)',
 '22(2)',
 '25(6)',
 '29(4)',
 '30(3)',
 '30(3)',
 '30(1)',
 '28(2)',
 '10(9)',
 '27(2)',
 '25(6)',
 '21(8)',
 '21(7)',
 '34',
 '31',
 '16(6)',
 '17(8)',
 '29(1)',
 '23(8)',
 '16(10)',
 '20(3)',
 '14(11)',
 '32',
 '23(6)',
 '28(2)',
 '27(4)',
 '15(9)',
 '30',
 '24(6)',
 '30',
 '22(5)',
 '20(8)',
 '27(3)',
 '31(1)',
 '33',
 '24(8)',
 '18(6)',
 '13(11)',
 '33',
 '32',
 '26',
 '21(12)',
 '31(2)',
 '26(6)',
 '18(6)',
 '10(9)',
 '32(1)',
 '22(3)',
 '30(2)',
 '19(9)',
 '28(1)',
 '21(11)',
 '20(11)',
 '34',
 '26',
 '11(13)',
 '27(3)',
 '32',
 '22(7)',
 '23(7)',
 '33',
 '27',
 '30(2)',
 '28(4)',
 '22(7)',
 '11(15)',
 '22(7)',
 '23(3)',
 '15(10)',
 '20(9)',
 '17(13)',
 '23(4)',
 '28(5)',
 '26(2)',
 '17(1)',
 '4(18)',
 '9(11)',
 '22(7)',
 '21(2)',
 '13(10)',
 '16(2)',
 '16(7)',
 '34',
 '32(2)',
 '16(15)',
 '25(4)',
 '20(7)',
 '23',
 '23(6)',
 '8(13)',
 '16(3)',
 '33',
 '16(14)',
 '28',
 '11(8)',
 '19(8)',
 '19(7)',
 '15(18)',
 '14(10)',
 '23(3)',
 '25(4)',
 '17(7)',
 '17(14)',
 '14(12)',
 '16(13)',
 '17(7)',
 '16(11)',
 '21(11)',
 '17(9)',
 '27(2)',
 '27(6)',
 '11(12)',
 '21(11)',
 '18',
 '6(17)',
 '25(3)',
 '15(16)',
 '17(9)',
 '30(1)',
 '24(6)',
 '29(2)',
 '16(7)',
 '16(7)',
 '7(12)',
 '8(15)',
 '33',
 '23(4)',
 '22',
 '22',
 '15(8)',
 '9(14)',
 '21(4)',
 '19(3)',
 '9(16)',
 '16(12)',
 '3(16)',
 '20(8)',
 '16(11)',
 '14(5)',
 '4(16)',
 '8(10)',
 '16(14)',
 '30(1)',
 '21(1)',
 '33',
 '14(9)',
 '13(10)',
 '15(3)',
 '19(9)',
 '14(5)',
 '1(21)',
 '26(3)',
 '7(14)',
 '23(6)',
 '19',
 '15(12)',
 '1(21)',
 '7(13)',
 '22(1)',
 '5(14)',
 '17(2)',
 '6(16)',
 '8(15)',
 '10(11)',
 '34',
 '20(7)',
 '8(10)',
 '8(12)',
 '10(11)',
 '12(6)',
 '3(15)',
 '18(13)',
 '2(19)',
 '7(17)',
 '3(21)',
 '8(21)',
 '10(22)',
 '8(14)',
 '2(19)',
 '3(20)',
 '8(16)',
 '8(12)',
 '4(20)',
 '4(14)',
 '14(6)',
 '11(12)',
 '19(8)',
 '7(13)',
 '19',
 '4(14)',
 '12(8)',
 '4(22)',
 '2(18)',
 '6(13)',
 '8(12)',
 '0(27)',
 '0(21)']

In [20]:
# ()안에 있는 숫자를 그냥 더해줌
# Apps값을 int형으로 변환

for i in range(286):
    if '(' in tmp_li[i]:
        tmp_li[i] = tmp_li[i].split('(')
        tmp_li[i] = [tmp_li[i][0], tmp_li[i][1].replace(')', '')]
        tmp_li[i] = int(tmp_li[i][0]) + int(tmp_li[i][1])
    else:
        tmp_li[i] = int(tmp_li[i])
    
tmp_df = pd.DataFrame(tmp_li, columns=['Apps'])
tmp_df

     Apps
0      31
1      33
2      28
3      25
4      33
..    ...
281    20
282    19
283    20
284    27
285    21

[286 rows x 1 columns]

In [21]:
BL_Player_df['Apps'] = tmp_df
BL_Player_df[['Apps']]

     Apps
0      31
1      33
2      28
3      25
4      33
..    ...
281    20
282    19
283    20
284    27
285    21

[286 rows x 1 columns]

In [22]:
# 추후 병합을 위해 Team이름을 맞춰준다.
player_team_df = BL_Player_df['Team']
player_team_list = player_team_df.to_list()


for i in range(len(player_team_list)): 
    player_team = player_team_list[i]
    
    if player_team == 'Bayern':
        player_team_list[i] = 'Bayern Munich'
    elif player_team == 'RBL':
        player_team_list[i] = 'RB Leipzig'
    elif player_team == 'Schalke':
        player_team_list[i] = 'Schalke 04'
    elif player_team == 'Mainz':
        player_team_list[i] = 'Mainz 05'
    elif player_team == 'Leverkusen':
        player_team_list[i] = 'Bayer Leverkusen'
    elif player_team == 'Stuttgart':
        player_team_list[i] = 'VfB Stuttgart'
        

BL_Player_df['Team'] = pd.DataFrame(player_team_list, columns=['Team'])
BL_Player_df['Team'].unique()

array(['Borussia Dortmund', 'Bayern Munich', 'Werder Bremen',
       'RB Leipzig', 'Eintracht Frankfurt', 'Freiburg',
       'Borussia M.Gladbach', 'FC Koln', 'Bayer Leverkusen', 'Wolfsburg',
       'Union Berlin', 'VfB Stuttgart', 'Bochum', 'Hoffenheim',
       'Schalke 04', 'Hertha Berlin', 'Mainz 05', 'Augsburg'],
      dtype=object)

In [24]:
BL_Player_df['Team'].unique()

array(['Borussia Dortmund', 'Bayern Munich', 'Werder Bremen',
       'RB Leipzig', 'Eintracht Frankfurt', 'Freiburg',
       'Borussia M.Gladbach', 'FC Koln', 'Bayer Leverkusen', 'Wolfsburg',
       'Union Berlin', 'VfB Stuttgart', 'Bochum', 'Hoffenheim',
       'Schalke 04', 'Hertha Berlin', 'Mainz 05', 'Augsburg'],
      dtype=object)

# Team 데이터 가져오기
- team table added

In [25]:
BL_Team_df = pd.read_csv('./Budesliga_data/Bundesliga_22_23_Team_Table_Added.csv')

In [27]:
BL_Team_df.columns

Index(['team_name', 'P', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Goals',
       'Shots pg', 'Yellow', 'Red', 'Poss%', 'Pass%', 'A_Won', 'Rating',
       'Shoted pg', 'Tackles pg', 'Intercept pg', 'Fouls pg', 'Offsides pg',
       'Shots OT pg', 'Dribbles pg', 'Fouled pg'],
      dtype='object')

In [28]:
BL_Team_df.columns = ['Team', 'P', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Goals',
       'Shots pg', 'Yellow', 'Red', 'Poss%', 'Pass%', 'A_Won', 'Rating',
       'Shoted pg', 'Tackles pg', 'Intercept pg', 'Fouls pg', 'Offsides pg',
       'Shots OT pg', 'Dribbles pg', 'Fouled pg']

In [31]:
# Team명이 통일되었는지 확인

for team in BL_Team_df['Team'].unique().tolist():
    if team not in BL_Player_df['Team'].unique().tolist():
        print(team)

# 포지션 구분
## 전처리 추가 필요 -> FW, AM, M, DM, D, GK

In [33]:
position_li = BL_Player_df['position'].unique().tolist()
position_li

['M(CLR)',
 'D(CR)',
 'FW',
 'M(CL)',
 'AM(CLR)',
 'AM(R)',
 'D(L)',
 'AM(CL)',
 'D(R)',
 'AM(LR)',
 'M(LR)',
 'D(CLR)',
 'D(C)',
 'AM(CR)',
 'AM(L)',
 'DMC',
 'M(CR)',
 'GK',
 'AM(C)',
 'D(CL)',
 'M(C)',
 'D(LR)',
 'M(L)',
 'Forward',
 'Midfielder']

In [35]:
# 각 포지션별로 데이터 추출

Position_df_li = []

for position in position_li:
    tmp = BL_Player_df[BL_Player_df['position'] == position]
    Position_df_li.append(tmp)

In [36]:
print(position_li[0])
Position_df_li[0]

M(CLR)

,player_name,team_number,Team,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Disp,UnsTch,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG
0,Jude Bellingham,44,Borussia Dortmund,19,M(CLR),31,2693,4,1.1,51.2,...,1.9,2.0,2.5,1.1,1.3,0.0,0.9,0.5,0.1,0
3,Christopher Nkunku,7614,RB Leipzig,25,M(CLR),25,1899,4,1.6,23.8,...,1.5,1.8,0.2,0.3,0.7,0.0,0.4,0.2,0.1,0
7,Julian Brandt,44,Borussia Dortmund,27,M(CLR),32,2412,8,2.3,37.0,...,1.1,1.6,0.9,0.5,0.3,0.0,0.3,1.0,0.0,0
14,Eric Choupo-Moting,37,Bayern Munich,34,M(CLR),19,1117,2,0.8,15.1,...,0.8,1.7,0.5,0.0,0.2,0.0,0.3,0.1,0.0,0
17,Thomas Müller,37,Bayern Munich,33,M(CLR),27,1672,8,1.4,28.7,...,0.7,1.8,0.8,0.1,0.3,0.0,0.5,0.4,0.1,0
23,Leroy Sané,37,Bayern Munich,27,M(CLR),32,2012,7,1.1,32.8,...,1.9,1.9,1.2,0.1,0.5,0.0,0.0,0.6,0.0,0
26,Moussa Diaby,36,Bayer Leverkusen,23,M(CLR),33,2716,8,1.8,26.4,...,1.3,1.9,0.4,0.2,0.5,0.0,0.1,0.2,0.0,0
67,Ihlas Bebou,1211,Hoffenheim,29,M(CLR),19,1423,0,0.8,17.6,...,0.9,3.2,1.0,0.4,1.2,0.0,0.8,0.3,0.1,0
76,Lars Stindl,134,Borussia M.Gladbach,34,M(CLR),29,1745,7,1.4,25.9,...,0.9,1.1,0.8,0.4,1.0,0.0,0.6,0.6,0.2,0
100,Marco Richter,47,Hertha Berlin,25,M(CLR),29,1844,5,0.7,20.0,...,1.2,2.0,1.5,0.8,1.2,0.0,0.6,1.0,0.1,0
110,Marco Reus,44,Borussia Dortmund,34,M(CLR),25,1352,4,0.8,21.8,...,0.6,1.2,1.2,0.3,0.7,0.0,0.3,0.7,0.2,0
124,Suat Serdar,47,Hertha Berlin,26,M(CLR),32,2034,2,0.6,19.0,...,1.0,1.1,1.6,0.9,1.0,0.0,0.7,0.7,0.4,0
128,Mario Götze,45,Eintracht Frankfurt,31,M(CLR),32,2749,1,1.3,43.8,...,1.4,1.8,1.3,0.4,0.8,0.0,0.3,1.0,0.0,0
130,Chris Führich,41,VfB Stuttgart,25,M(CLR),33,1892,2,0.7,19.1,...,0.9,1.1,1.1,0.2,0.2,0.0,0.3,0.6,0.1,0
134,Roland Sallai,50,Freiburg,26,M(CLR),19,1003,3,0.9,15.7,...,0.5,1.1,0.6,0.1,1.5,0.0,0.6,0.3,0.1,0
136,Leonardo Bittencourt,42,Werder Bremen,29,M(CLR),25,1644,2,0.6,28.4,...,0.4,1.7,2.1,0.4,1.7,0.0,0.5,1.5,0.0,0
137,Janik Haberer,796,Union Berlin,29,M(CLR),32,2213,1,0.7,20.3,...,0.6,1.1,0.9,0.4,1.1,0.0,0.8,1.0,0.1,0
140,Mattias Svanberg,33,Wolfsburg,24,M(CLR),32,1836,6,0.8,16.4,...,0.6,1.5,0.8,0.7,0.8,0.0,0.7,0.6,0.2,0
148,Silas Katompa Mvumpa,41,VfB Stuttgart,24,M(CLR),30,2004,2,0.6,11.8,...,1.5,2.3,0.8,0.3,1.3,0.1,0.0,0.5,0.1,0
157,Philipp Förster,109,Bochum,28,M(CLR),25,1313,7,1.1,18.2,...,0.6,0.9,1.2,0.2,1.1,0.0,0.2,1.1,0.0,0
199,Linton Maina,282,FC Koln,24,M(CLR),33,2258,7,1.1,17.6,...,0.8,1.7,0.5,0.2,0.5,0.0,0.3,0.7,0.0,0
205,Amadou Haidara,7614,RB Leipzig,25,M(CLR),31,1430,1,0.4,26.2,...,0.4,0.4,0.8,0.8,0.9,0.0,0.6,0.7,0.2,0
222,Nadiem Amiri,36,Bayer Leverkusen,26,M(CLR),25,970,1,0.6,19.4,...,0.4,0.6,0.6,0.2,0.6,0.0,0.2,0.4,0.0,0
230,Kevin Kampl,7614,RB Leipzig,32,M(CLR),30,1371,2,0.4,29.7,...,0.3,0.6,0.7,0.7,0.7,0.0,0.4,0.7,0.3,0
269,Morten Thorsby,796,Union Berlin,27,M(CLR),24,827,1,0.3,7.8,...,0.6,0.6,0.9,0.1,0.9,0.0,0.8,0.3,0.2,0
272,Hannes Wolf,134,Borussia M.Gladbach,24,M(CLR),18,441,1,0.3,9.4,...,0.7,0.4,0.6,0.2,0.4,0.0,0.5,0.4,0.0,0

In [39]:
# 포지션 압축
# M, FW, AM, D, DMC, M, GK, Forward

tmp_df = BL_Player_df['position']
tmp_li = tmp_df.tolist()
tmp_li

['M(CLR)',
 'D(CR)',
 'FW',
 'M(CLR)',
 'M(CL)',
 'AM(CLR)',
 'AM(R)',
 'M(CLR)',
 'D(L)',
 'AM(CL)',
 'D(R)',
 'FW',
 'AM(LR)',
 'M(LR)',
 'M(CLR)',
 'D(CLR)',
 'D(L)',
 'M(CLR)',
 'D(C)',
 'D(R)',
 'AM(CR)',
 'AM(CLR)',
 'AM(L)',
 'M(CLR)',
 'D(C)',
 'AM(CLR)',
 'M(CLR)',
 'D(C)',
 'DMC',
 'M(CR)',
 'GK',
 'D(L)',
 'FW',
 'D(CR)',
 'D(L)',
 'AM(C)',
 'AM(R)',
 'D(L)',
 'D(C)',
 'D(C)',
 'DMC',
 'D(CL)',
 'D(CR)',
 'D(R)',
 'D(C)',
 'AM(CLR)',
 'AM(CLR)',
 'AM(CLR)',
 'M(CR)',
 'AM(CLR)',
 'D(C)',
 'M(CR)',
 'D(CLR)',
 'DMC',
 'D(C)',
 'M(C)',
 'D(C)',
 'D(LR)',
 'D(R)',
 'M(C)',
 'AM(LR)',
 'AM(CLR)',
 'M(C)',
 'AM(CLR)',
 'AM(CLR)',
 'M(CL)',
 'FW',
 'M(CLR)',
 'AM(CLR)',
 'AM(CLR)',
 'M(C)',
 'D(R)',
 'D(R)',
 'DMC',
 'D(C)',
 'D(CR)',
 'M(CLR)',
 'AM(CLR)',
 'GK',
 'GK',
 'D(CR)',
 'D(C)',
 'GK',
 'AM(CLR)',
 'GK',
 'D(CR)',
 'AM(L)',
 'D(LR)',
 'AM(L)',
 'D(CR)',
 'D(C)',
 'DMC',
 'D(R)',
 'D(L)',
 'D(R)',
 'D(C)',
 'D(C)',
 'M(CR)',
 'D(C)',
 'M(LR)',
 'M(CLR)',
 'D(CR)',
 'GK',
 'D(C)',
 'M(C)',
 'M(C)',
 'D(CL)',
 'D(CLR)',
 'AM(CLR)',
 'AM(C)',
 'M(CLR)',
 'D(CLR)',
 'DMC',
 'D(C)',
 'M(CR)',
 'AM(C)',
 'D(CL)',
 'D(CL)',
 'D(CL)',
 'AM(CR)',
 'D(L)',
 'D(CL)',
 'DMC',
 'D(CL)',
 'M(CLR)',
 'D(C)',
 'D(L)',
 'D(C)',
 'M(CLR)',
 'GK',
 'M(CLR)',
 'D(L)',
 'AM(CLR)',
 'D(CR)',
 'M(CLR)',
 'D(C)',
 'M(CLR)',
 'M(CLR)',
 'D(L)',
 'D(CR)',
 'M(CLR)',
 'FW',
 'GK',
 'GK',
 'AM(C)',
 'DMC',
 'D(C)',
 'D(L)',
 'M(CLR)',
 'GK',
 'M(C)',
 'M(C)',
 'D(C)',
 'D(C)',
 'FW',
 'AM(CLR)',
 'D(C)',
 'M(CLR)',
 'AM(CLR)',
 'FW',
 'D(C)',
 'D(C)',
 'D(C)',
 'M(C)',
 'AM(CLR)',
 'AM(CLR)',
 'D(C)',
 'D(C)',
 'AM(CLR)',
 'FW',
 'D(L)',
 'D(CR)',
 'D(CL)',
 'FW',
 'D(LR)',
 'M(CR)',
 'D(L)',
 'D(C)',
 'AM(C)',
 'D(C)',
 'GK',
 'AM(CLR)',
 'D(CR)',
 'D(LR)',
 'D(R)',
 'D(CR)',
 'AM(L)',
 'M(LR)',
 'D(C)',
 'D(C)',
 'D(CR)',
 'D(CL)',
 'D(CL)',
 'AM(CL)',
 'D(CR)',
 'AM(CLR)',
 'FW',
 'M(C)',
 'M(C)',
 'M(CLR)',
 'D(C)',
 'M(C)',
 'M(C)',
 'AM(CLR)',
 'D(R)',
 'M(CLR)',
 'D(R)',
 'D(CLR)',
 'M(CR)',
 'D(L)',
 'D(LR)',
 'M(C)',
 'FW',
 'AM(C)',
 'GK',
 'D(CR)',
 'D(CR)',
 'D(CLR)',
 'FW',
 'AM(C)',
 'AM(CLR)',
 'D(L)',
 'M(CLR)',
 'AM(CR)',
 'AM(R)',
 'D(L)',
 'AM(CLR)',
 'D(C)',
 'D(R)',
 'D(L)',
 'M(CLR)',
 'M(C)',
 'D(CR)',
 'GK',
 'D(R)',
 'D(C)',
 'D(CR)',
 'D(L)',
 'D(CL)',
 'M(L)',
 'DMC',
 'DMC',
 'D(CLR)',
 'GK',
 'AM(CL)',
 'Forward',
 'D(L)',
 'GK',
 'AM(R)',
 'D(R)',
 'D(R)',
 'D(L)',
 'AM(CLR)',
 'GK',
 'D(C)',
 'FW',
 'AM(CL)',
 'AM(CL)',
 'DMC',
 'Midfielder',
 'DMC',
 'D(L)',
 'AM(C)',
 'DMC',
 'D(R)',
 'AM(C)',
 'DMC',
 'AM(L)',
 'AM(CR)',
 'M(CLR)',
 'D(R)',
 'AM(CLR)',
 'M(CLR)',
 'D(C)',
 'DMC',
 'AM(LR)',
 'AM(R)',
 'GK',
 'AM(CLR)',
 'D(R)',
 'AM(CR)',
 'FW',
 'FW',
 'M(C)',
 'FW',
 'M(LR)']

In [43]:
# 포지션 압축

for i in range(len(tmp_li)):
    pos_tmp = tmp_li[i]
    if '(' in pos_tmp:
        pos_tmp_li = pos_tmp.split('(')
        tmp_li[i] = pos_tmp_li[0]
    
    if tmp_li[i] == 'Forward':
        tmp_li[i] = 'FW'
        
    elif tmp_li[i] == 'DMC':
        tmp_li[i] = 'DM'
        
    elif tmp_li[i] == 'Midfielder':
        tmp_li[i] = 'M'

In [44]:
# 원본 데이터에 적용

BL_Player_df['position'] = pd.DataFrame(tmp_li, columns=['position'])

In [45]:
# 적용되었는지 확인

BL_Player_df['position'].unique()

array(['M', 'D', 'FW', 'AM', 'DM', 'GK'], dtype=object)

# 포지션별 dataframe 생성
- csv파일도 생성

In [56]:
FW_player_df = BL_Player_df[BL_Player_df['position'] == 'FW']
print(FW_player_df.shape)
#FW_player_df.to_csv('BL_FW_Player.csv', encoding='utf-8-sig')

(17, 34)

In [57]:
AM_player_df = BL_Player_df[BL_Player_df['position'] == 'AM']
AM_player_df.shape
#AM_player_df.to_csv('BL_AM_Player.csv', encoding='utf-8-sig')

(61, 34)

In [58]:
M_player_df = BL_Player_df[BL_Player_df['position'] == 'M']
M_player_df.shape
#M_player_df.to_csv('BL_M_Player.csv', encoding='utf-8-sig')

(57, 34)

In [59]:
DM_player_df = BL_Player_df[BL_Player_df['position'] == 'DM']
DM_player_df.shape
#DM_player_df.to_csv('BL_DM_Player.csv', encoding='utf-8-sig')

(15, 34)

In [60]:
D_player_df = BL_Player_df[BL_Player_df['position'] == 'D']
D_player_df.shape
#D_player_df.to_csv('BL_D_Player.csv', encoding='utf-8-sig')

(119, 34)

In [61]:
GK_player_df = BL_Player_df[BL_Player_df['position'] == 'GK']
GK_player_df.shape
#GK_player_df.to_csv('BL_GK_Player.csv', encoding='utf-8-sig')

(17, 34)