# 데이터를 사용하기 좋게 미리 일정 부분 조정 및 새로운 데이터 생성

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Laliga 선수 데이터 확인

In [2]:
LL_Player_df = pd.read_csv('./Laliga_data/Laliga_Player_22_23.csv')

In [3]:
LL_Player_df.head()

,Unnamed: 0,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,...,Disp,UnsTch,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG
0,0,Antoine Griezmann,63,Atletico,32,"AM(CLR),FW",31(7),2863,16,2.2,...,0.9,1.1,1.3,0.6,0.6,0.0,0.8,1.2,0.1,0
1,1,Karim Benzema,52,Real Madrid,35,FW,24,2044,3,2.0,...,1.2,1.3,0.4,0.1,0.4,0.0,0.2,0.4,0.0,0
2,2,Robert Lewandowski,65,Barcelona,34,FW,33(1),2852,7,1.1,...,1.5,2.8,0.5,0.1,1.1,0.1,0.4,0.2,0.0,0
3,3,Vinícius Júnior,52,Real Madrid,22,"AM(L),FW",32(1),2833,9,1.9,...,1.8,3.1,0.9,0.2,1.4,0.0,0.0,0.8,0.0,0
4,4,Rodrygo,52,Real Madrid,22,"AM(CLR),FW",25(9),2382,8,1.4,...,0.9,1.9,0.5,0.2,0.5,0.0,0.1,0.6,0.0,0

In [4]:
LL_Player_df.drop('Unnamed: 0', axis=1, inplace=True)
LL_Player_df

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Disp,UnsTch,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG
0,Antoine Griezmann,63,Atletico,32,"AM(CLR),FW",31(7),2863,16,2.2,38.3,...,0.9,1.1,1.3,0.6,0.6,0.0,0.8,1.2,0.1,0
1,Karim Benzema,52,Real Madrid,35,FW,24,2044,3,2.0,44.0,...,1.2,1.3,0.4,0.1,0.4,0.0,0.2,0.4,0.0,0
2,Robert Lewandowski,65,Barcelona,34,FW,33(1),2852,7,1.1,22.4,...,1.5,2.8,0.5,0.1,1.1,0.1,0.4,0.2,0.0,0
3,Vinícius Júnior,52,Real Madrid,22,"AM(L),FW",32(1),2833,9,1.9,32.1,...,1.8,3.1,0.9,0.2,1.4,0.0,0.0,0.8,0.0,0
4,Rodrygo,52,Real Madrid,22,"AM(CLR),FW",25(9),2382,8,1.4,29.7,...,0.9,1.9,0.5,0.2,0.5,0.0,0.1,0.6,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,Antonio Sánchez,51,Mallorca,26,M(CR),11(21),1066,0,0.2,12.2,...,0.6,0.8,0.6,0.7,0.8,0.0,0.2,0.8,0.0,0
339,Abdón Prats,51,Mallorca,30,FW,2(24),398,1,0.3,3.5,...,0.5,0.3,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0
340,Raúl Guti,833,Elche,26,DMC,12(16),1084,0,0.1,14.2,...,0.6,0.5,0.6,0.3,0.3,0.0,0.2,0.4,0.1,0
341,Radamel Falcao,64,Rayo Vallecano,37,FW,3(24),598,0,0.1,6.1,...,0.3,1.1,0.1,0.1,0.6,0.0,0.4,0.3,0.0,0
342,Salvi Sánchez,64,Rayo Vallecano,32,AM(R),4(20),475,0,0.3,6.3,...,0.3,0.4,0.5,0.1,0.3,0.0,0.0,0.3,0.0,0

In [5]:
# team_name -> Team으로 변경
# EPL, Bundesliga는 Team으로 바꿔줬는데 일단 여기서는 안 건드림

'''
LL_Player_df.columns = ['player_name', 'team_number', 'Team', 'age', 'position', 'Apps',
       'Mins', 'Assists', 'KeyP', 'AvgP', 'PS%', 'Crosses', 'LongB', 'ThrB',
       'Rating', 'Goals', 'Yel', 'Red', 'SpG', 'AerialsWon', 'MoM', 'Dribble',
       'Fouled', 'Off', 'Disp', 'UnsTch', 'Tackles', 'Inter', 'Fouls',
       'Offsides', 'Clear', 'Drb', 'Blocks', 'OwnG']
'''

"\nLL_Player_df.columns = ['player_name', 'team_number', 'Team', 'age', 'position', 'Apps',\n       'Mins', 'Assists', 'KeyP', 'AvgP', 'PS%', 'Crosses', 'LongB', 'ThrB',\n       'Rating', 'Goals', 'Yel', 'Red', 'SpG', 'AerialsWon', 'MoM', 'Dribble',\n       'Fouled', 'Off', 'Disp', 'UnsTch', 'Tackles', 'Inter', 'Fouls',\n       'Offsides', 'Clear', 'Drb', 'Blocks', 'OwnG']\n"

In [6]:
LL_Player_df.shape

(343, 34)

In [7]:
LL_Player_df.columns

Index(['player_name', 'team_number', 'team_name', 'age', 'position', 'Apps',
       'Mins', 'Assists', 'KeyP', 'AvgP', 'PS%', 'Crosses', 'LongB', 'ThrB',
       'Rating', 'Goals', 'Yel', 'Red', 'SpG', 'AerialsWon', 'MoM', 'Dribble',
       'Fouled', 'Off', 'Disp', 'UnsTch', 'Tackles', 'Inter', 'Fouls',
       'Offsides', 'Clear', 'Drb', 'Blocks', 'OwnG'],
      dtype='object')

In [8]:
# 결측치 유무 확인
LL_Player_df.isna().sum()

player_name    0
team_number    0
team_name      0
age            0
position       0
Apps           0
Mins           0
Assists        0
KeyP           0
AvgP           0
PS%            0
Crosses        0
LongB          0
ThrB           0
Rating         0
Goals          0
Yel            0
Red            0
SpG            0
AerialsWon     0
MoM            0
Dribble        0
Fouled         0
Off            0
Disp           0
UnsTch         0
Tackles        0
Inter          0
Fouls          0
Offsides       0
Clear          0
Drb            0
Blocks         0
OwnG           0
dtype: int64

## 포지션 전처리

In [9]:
LL_Player_df['position'].unique()

array([' AM(CLR),FW  ', ' FW  ', ' AM(L),FW  ', ' AM(CL)  ',
       ' D(C),DMC  ', ' M(C)  ', ' M(CLR)  ', ' M(CL)  ', ' D(CR),DMC  ',
       ' AM(R)  ', ' AM(LR),FW  ', ' DMC  ', ' GK  ', ' D(CR)  ',
       ' D(L),M(L)  ', ' AM(CR),FW  ', ' D(C)  ', ' AM(CLR)  ',
       ' AM(LR)  ', ' AM(C)  ', ' D(CL),M(L)  ', ' D(LR)  ', ' AM(CR)  ',
       ' D(L),M(CLR),FW  ', ' AM(R),FW  ', ' M(CLR),FW  ', ' M(CR),FW  ',
       ' AM(L)  ', ' D(L)  ', ' D(R),M(CR),FW  ', ' D(R),M(R)  ',
       ' D(R)  ', ' D(L),DMC  ', ' D(LR),M(R)  ', ' D(CL),M(CL)  ',
       ' D(LR),M(CLR),FW  ', ' M(C),FW  ', ' D(CL)  ', ' D(C),M(CL)  ',
       ' D(R),M(LR)  ', ' D(C),M(C)  ', ' D(LR),M(CR)  ', ' D(R),M(CR)  ',
       ' M(LR)  ', ' D(CR),M(R)  ', ' D(CLR)  ', ' D(CL),M(CLR)  ',
       ' D(LR),M(LR)  ', ' D(LR),M(L)  ', ' D(L),M(CL)  ',
       ' D(R),M(CLR),FW  ', ' D(R),M(C)  ', ' D(CLR),M(R)  ', ' M(CR)  ',
       ' M(CL),FW  ', ' D(R),M(L)  ', ' AM(C),FW  ', ' DMC,M(R)  '],
      dtype=object)

In [10]:
# 전체 데이터에서 position 데이터만 추출

position_df = LL_Player_df[['position']]
position_df

          position
0     AM(CLR),FW
1             FW
2             FW
3       AM(L),FW
4     AM(CLR),FW
..             ...
338        M(CR)
339           FW
340          DMC
341           FW
342        AM(R)

[343 rows x 1 columns]

In [11]:
# 리스트 형태로 변환

tmp_li = position_df['position'].tolist()
tmp_li

[' AM(CLR),FW  ',
 ' FW  ',
 ' FW  ',
 ' AM(L),FW  ',
 ' AM(CLR),FW  ',
 ' AM(CL)  ',
 ' FW  ',
 ' D(C),DMC  ',
 ' AM(CLR),FW  ',
 ' M(C)  ',
 ' AM(CLR),FW  ',
 ' M(CLR)  ',
 ' M(CL)  ',
 ' FW  ',
 ' D(CR),DMC  ',
 ' AM(R)  ',
 ' AM(LR),FW  ',
 ' M(C)  ',
 ' DMC  ',
 ' DMC  ',
 ' GK  ',
 ' D(CR)  ',
 ' FW  ',
 ' DMC  ',
 ' AM(CLR),FW  ',
 ' DMC  ',
 ' D(L),M(L)  ',
 ' D(L),M(L)  ',
 ' D(CR)  ',
 ' D(CR)  ',
 ' M(C)  ',
 ' AM(CLR),FW  ',
 ' GK  ',
 ' AM(CR),FW  ',
 ' AM(CR),FW  ',
 ' D(C)  ',
 ' AM(CR),FW  ',
 ' AM(CLR)  ',
 ' D(CR)  ',
 ' AM(LR)  ',
 ' AM(C)  ',
 ' D(CL),M(L)  ',
 ' D(LR)  ',
 ' AM(LR)  ',
 ' AM(CR)  ',
 ' D(C)  ',
 ' FW  ',
 ' AM(CLR),FW  ',
 ' GK  ',
 ' D(L),M(CLR),FW  ',
 ' AM(R),FW  ',
 ' M(CLR),FW  ',
 ' AM(L),FW  ',
 ' GK  ',
 ' M(C)  ',
 ' GK  ',
 ' AM(CL)  ',
 ' AM(CLR),FW  ',
 ' GK  ',
 ' M(CR),FW  ',
 ' D(L),M(L)  ',
 ' D(C),DMC  ',
 ' AM(L)  ',
 ' AM(C)  ',
 ' AM(LR),FW  ',
 ' D(L)  ',
 ' D(R),M(CR),FW  ',
 ' AM(CLR),FW  ',
 ' D(C)  ',
 ' AM(CLR),FW  ',
 ' D(L),M(L)  ',
 ' D(C)  ',
 ' D(R),M(R)  ',
 ' AM(L),FW  ',
 ' D(R)  ',
 ' D(L),DMC  ',
 ' D(LR),M(R)  ',
 ' D(LR),M(R)  ',
 ' D(CL),M(CL)  ',
 ' M(C)  ',
 ' D(C)  ',
 ' D(C)  ',
 ' D(C),DMC  ',
 ' AM(R),FW  ',
 ' D(CL),M(L)  ',
 ' M(CL)  ',
 ' DMC  ',
 ' D(LR),M(CLR),FW  ',
 ' D(C)  ',
 ' D(C)  ',
 ' D(R)  ',
 ' D(C)  ',
 ' D(C)  ',
 ' GK  ',
 ' AM(CLR)  ',
 ' D(L)  ',
 ' M(C),FW  ',
 ' D(CL)  ',
 ' M(C)  ',
 ' M(CLR)  ',
 ' D(L)  ',
 ' D(C),M(CL)  ',
 ' M(CLR)  ',
 ' D(C)  ',
 ' AM(LR),FW  ',
 ' DMC  ',
 ' M(CLR),FW  ',
 ' GK  ',
 ' AM(R),FW  ',
 ' M(CLR)  ',
 ' DMC  ',
 ' DMC  ',
 ' D(R),M(R)  ',
 ' D(C)  ',
 ' GK  ',
 ' FW  ',
 ' FW  ',
 ' GK  ',
 ' GK  ',
 ' AM(L),FW  ',
 ' D(L),M(L)  ',
 ' D(R),M(LR)  ',
 ' DMC  ',
 ' D(R),M(R)  ',
 ' AM(CLR),FW  ',
 ' GK  ',
 ' D(C),DMC  ',
 ' D(C),M(C)  ',
 ' DMC  ',
 ' AM(CLR),FW  ',
 ' AM(LR),FW  ',
 ' D(LR),M(CR)  ',
 ' GK  ',
 ' D(C)  ',
 ' D(L),M(L)  ',
 ' AM(L)  ',
 ' D(C)  ',
 ' M(C)  ',
 ' D(C)  ',
 ' D(R),M(CR)  ',
 ' D(C)  ',
 ' D(C)  ',
 ' D(C),DMC  ',
 ' AM(LR)  ',
 ' M(LR)  ',
 ' D(CR),M(R)  ',
 ' M(CLR),FW  ',
 ' AM(CLR)  ',
 ' DMC  ',
 ' D(CL),M(L)  ',
 ' FW  ',
 ' AM(C)  ',
 ' AM(CL)  ',
 ' DMC  ',
 ' D(C)  ',
 ' D(CLR)  ',
 ' D(C)  ',
 ' D(L)  ',
 ' AM(LR)  ',
 ' AM(CLR),FW  ',
 ' D(C)  ',
 ' D(CLR)  ',
 ' D(CL)  ',
 ' D(C)  ',
 ' AM(CLR)  ',
 ' AM(CR),FW  ',
 ' D(C)  ',
 ' AM(LR)  ',
 ' DMC  ',
 ' AM(CL)  ',
 ' AM(LR),FW  ',
 ' D(C)  ',
 ' DMC  ',
 ' D(CL),M(CL)  ',
 ' D(C)  ',
 ' M(CLR)  ',
 ' GK  ',
 ' M(C),FW  ',
 ' D(C),DMC  ',
 ' M(CL)  ',
 ' D(C),DMC  ',
 ' AM(CLR),FW  ',
 ' M(C)  ',
 ' D(C)  ',
 ' AM(CR)  ',
 ' AM(CLR)  ',
 ' D(L)  ',
 ' D(R)  ',
 ' AM(CLR),FW  ',
 ' D(CL),M(CLR)  ',
 ' M(C)  ',
 ' FW  ',
 ' DMC  ',
 ' D(C),DMC  ',
 ' M(CLR)  ',
 ' AM(L),FW  ',
 ' M(C)  ',
 ' AM(L),FW  ',
 ' D(C),M(C)  ',
 ' D(LR),M(LR)  ',
 ' M(C)  ',
 ' D(R),M(R)  ',
 ' FW  ',
 ' D(C)  ',
 ' GK  ',
 ' M(CL)  ',
 ' D(L)  ',
 ' AM(CLR),FW  ',
 ' D(R),M(LR)  ',
 ' D(C),DMC  ',
 ' D(C)  ',
 ' D(CL),M(L)  ',
 ' D(CLR)  ',
 ' D(C)  ',
 ' DMC  ',
 ' D(C),DMC  ',
 ' D(LR),M(L)  ',
 ' D(R),M(R)  ',
 ' D(CL),M(L)  ',
 ' GK  ',
 ' FW  ',
 ' AM(CLR),FW  ',
 ' D(L),M(CL)  ',
 ' AM(CLR),FW  ',
 ' D(LR),M(R)  ',
 ' AM(CLR),FW  ',
 ' D(C)  ',
 ' AM(R),FW  ',
 ' DMC  ',
 ' D(L)  ',
 ' DMC  ',
 ' D(R)  ',
 ' D(CL)  ',
 ' AM(CLR)  ',
 ' AM(LR),FW  ',
 ' D(R),M(R)  ',
 ' D(R),M(CLR),FW  ',
 ' FW  ',
 ' GK  ',
 ' D(C)  ',
 ' M(C)  ',
 ' AM(CLR)  ',
 ' DMC  ',
 ' FW  ',
 ' D(C),DMC  ',
 ' D(L),M(L)  ',
 ' D(CR)  ',
 ' M(C)  ',
 ' D(C)  ',
 ' D(CR)  ',
 ' D(R),M(R)  ',
 ' D(R)  ',
 ' M(C)  ',
 ' D(L)  ',
 ' D(C),DMC  ',
 ' FW  ',
 ' D(C),DMC  ',
 ' GK  ',
 ' D(LR),M(R)  ',
 ' D(R),M(C)  ',
 ' AM(CLR),FW  ',
 ' D(R)  ',
 ' D(R),M(R)  ',
 ' D(CR)  ',
 ' AM(CLR),FW  ',
 ' D(R),M(R)  ',
 ' D(CR)  ',
 ' D(L),M(L)  ',
 ' M(CLR),FW  ',
 ' AM(LR),FW  ',
 ' AM(CLR),FW  ',
 ' D(L)  ',
 ' GK  ',
 ' AM(CR)  ',
 ' AM(CLR),FW  ',
 ' GK  ',
 ' D(CR)  ',
 ' D(CL)  ',
 ' D(R)  ',
 ' DMC  ',
 ' DMC  ',
 ' M(CLR)  ',
 ' D(CLR),M(R)  ',
 ' FW  ',
 ' DMC  ',
 ' D(C)  ',
 ' D(C),DMC  ',
 ' D(C)  ',
 ' M(C)  ',
 ' D(CR)  ',
 ' AM(CL)  ',
 ' D(CL)  ',
 ' D(CR),M(R)  ',
 ' M(CR)  ',
 ' M(C)  ',
 ' DMC  ',
 ' D(C)  ',
 ' FW  ',
 ' M(CL),FW  ',
 ' M(CR)  ',
 ' D(CR)  ',
 ' AM(C)  ',
 ' M(CLR),FW  ',
 ' AM(CLR),FW  ',
 ' D(L),M(L)  ',
 ' AM(CLR),FW  ',
 ' AM(L),FW  ',
 ' M(CL)  ',
 ' AM(L),FW  ',
 ' M(C)  ',
 ' M(CLR),FW  ',
 ' D(R),M(L)  ',
 ' M(C)  ',
 ' M(CLR),FW  ',
 ' DMC  ',
 ' M(C)  ',
 ' AM(LR),FW  ',
 ' FW  ',
 ' FW  ',
 ' M(CLR),FW  ',
 ' D(C)  ',
 ' M(CLR)  ',
 ' AM(CLR)  ',
 ' D(R),M(LR)  ',
 ' AM(C),FW  ',
 ' AM(L),FW  ',
 ' AM(R)  ',
 ' FW  ',
 ' FW  ',
 ' AM(R)  ',
 ' DMC  ',
 ' M(C)  ',
 ' FW  ',
 ' DMC,M(R)  ',
 ' M(CL)  ',
 ' DMC  ',
 ' AM(L),FW  ',
 ' AM(L),FW  ',
 ' M(CR)  ',
 ' FW  ',
 ' DMC  ',
 ' FW  ',
 ' AM(R)  ']

In [12]:
# 포지션이 여러 개인 경우 하나의 포지션만 남긴다.

for i in range(len(tmp_li)):
    tmp = tmp_li[i]
    if ',' in tmp:
        tmp_li[i] = tmp.split(',')[0]

In [13]:
tmp = pd.DataFrame(tmp_li)
tmp.columns = ['position']
tmp

     position
0     AM(CLR)
1        FW
2        FW
3       AM(L)
4     AM(CLR)
..        ...
338   M(CR)
339      FW
340     DMC
341      FW
342   AM(R)

[343 rows x 1 columns]

In [14]:
# 전체 데이터에 새로운 포지션 값 적용

LL_Player_df['position'] = tmp['position']
LL_Player_df['position'] # 변경이 되었는지 확인

0       AM(CLR)
1          FW
2          FW
3         AM(L)
4       AM(CLR)
         ...
338     M(CR)
339        FW
340       DMC
341        FW
342     AM(R)
Name: position, Length: 343, dtype: object

In [15]:
# unique값 확인
# 공백이 있는 경우 같은 포지션도 다르게 판단 -> 공백을 지워준다.

tmp_li = LL_Player_df['position'].tolist()
tmp_li

[' AM(CLR)',
 ' FW  ',
 ' FW  ',
 ' AM(L)',
 ' AM(CLR)',
 ' AM(CL)  ',
 ' FW  ',
 ' D(C)',
 ' AM(CLR)',
 ' M(C)  ',
 ' AM(CLR)',
 ' M(CLR)  ',
 ' M(CL)  ',
 ' FW  ',
 ' D(CR)',
 ' AM(R)  ',
 ' AM(LR)',
 ' M(C)  ',
 ' DMC  ',
 ' DMC  ',
 ' GK  ',
 ' D(CR)  ',
 ' FW  ',
 ' DMC  ',
 ' AM(CLR)',
 ' DMC  ',
 ' D(L)',
 ' D(L)',
 ' D(CR)  ',
 ' D(CR)  ',
 ' M(C)  ',
 ' AM(CLR)',
 ' GK  ',
 ' AM(CR)',
 ' AM(CR)',
 ' D(C)  ',
 ' AM(CR)',
 ' AM(CLR)  ',
 ' D(CR)  ',
 ' AM(LR)  ',
 ' AM(C)  ',
 ' D(CL)',
 ' D(LR)  ',
 ' AM(LR)  ',
 ' AM(CR)  ',
 ' D(C)  ',
 ' FW  ',
 ' AM(CLR)',
 ' GK  ',
 ' D(L)',
 ' AM(R)',
 ' M(CLR)',
 ' AM(L)',
 ' GK  ',
 ' M(C)  ',
 ' GK  ',
 ' AM(CL)  ',
 ' AM(CLR)',
 ' GK  ',
 ' M(CR)',
 ' D(L)',
 ' D(C)',
 ' AM(L)  ',
 ' AM(C)  ',
 ' AM(LR)',
 ' D(L)  ',
 ' D(R)',
 ' AM(CLR)',
 ' D(C)  ',
 ' AM(CLR)',
 ' D(L)',
 ' D(C)  ',
 ' D(R)',
 ' AM(L)',
 ' D(R)  ',
 ' D(L)',
 ' D(LR)',
 ' D(LR)',
 ' D(CL)',
 ' M(C)  ',
 ' D(C)  ',
 ' D(C)  ',
 ' D(C)',
 ' AM(R)',
 ' D(CL)',
 ' M(CL)  ',
 ' DMC  ',
 ' D(LR)',
 ' D(C)  ',
 ' D(C)  ',
 ' D(R)  ',
 ' D(C)  ',
 ' D(C)  ',
 ' GK  ',
 ' AM(CLR)  ',
 ' D(L)  ',
 ' M(C)',
 ' D(CL)  ',
 ' M(C)  ',
 ' M(CLR)  ',
 ' D(L)  ',
 ' D(C)',
 ' M(CLR)  ',
 ' D(C)  ',
 ' AM(LR)',
 ' DMC  ',
 ' M(CLR)',
 ' GK  ',
 ' AM(R)',
 ' M(CLR)  ',
 ' DMC  ',
 ' DMC  ',
 ' D(R)',
 ' D(C)  ',
 ' GK  ',
 ' FW  ',
 ' FW  ',
 ' GK  ',
 ' GK  ',
 ' AM(L)',
 ' D(L)',
 ' D(R)',
 ' DMC  ',
 ' D(R)',
 ' AM(CLR)',
 ' GK  ',
 ' D(C)',
 ' D(C)',
 ' DMC  ',
 ' AM(CLR)',
 ' AM(LR)',
 ' D(LR)',
 ' GK  ',
 ' D(C)  ',
 ' D(L)',
 ' AM(L)  ',
 ' D(C)  ',
 ' M(C)  ',
 ' D(C)  ',
 ' D(R)',
 ' D(C)  ',
 ' D(C)  ',
 ' D(C)',
 ' AM(LR)  ',
 ' M(LR)  ',
 ' D(CR)',
 ' M(CLR)',
 ' AM(CLR)  ',
 ' DMC  ',
 ' D(CL)',
 ' FW  ',
 ' AM(C)  ',
 ' AM(CL)  ',
 ' DMC  ',
 ' D(C)  ',
 ' D(CLR)  ',
 ' D(C)  ',
 ' D(L)  ',
 ' AM(LR)  ',
 ' AM(CLR)',
 ' D(C)  ',
 ' D(CLR)  ',
 ' D(CL)  ',
 ' D(C)  ',
 ' AM(CLR)  ',
 ' AM(CR)',
 ' D(C)  ',
 ' AM(LR)  ',
 ' DMC  ',
 ' AM(CL)  ',
 ' AM(LR)',
 ' D(C)  ',
 ' DMC  ',
 ' D(CL)',
 ' D(C)  ',
 ' M(CLR)  ',
 ' GK  ',
 ' M(C)',
 ' D(C)',
 ' M(CL)  ',
 ' D(C)',
 ' AM(CLR)',
 ' M(C)  ',
 ' D(C)  ',
 ' AM(CR)  ',
 ' AM(CLR)  ',
 ' D(L)  ',
 ' D(R)  ',
 ' AM(CLR)',
 ' D(CL)',
 ' M(C)  ',
 ' FW  ',
 ' DMC  ',
 ' D(C)',
 ' M(CLR)  ',
 ' AM(L)',
 ' M(C)  ',
 ' AM(L)',
 ' D(C)',
 ' D(LR)',
 ' M(C)  ',
 ' D(R)',
 ' FW  ',
 ' D(C)  ',
 ' GK  ',
 ' M(CL)  ',
 ' D(L)  ',
 ' AM(CLR)',
 ' D(R)',
 ' D(C)',
 ' D(C)  ',
 ' D(CL)',
 ' D(CLR)  ',
 ' D(C)  ',
 ' DMC  ',
 ' D(C)',
 ' D(LR)',
 ' D(R)',
 ' D(CL)',
 ' GK  ',
 ' FW  ',
 ' AM(CLR)',
 ' D(L)',
 ' AM(CLR)',
 ' D(LR)',
 ' AM(CLR)',
 ' D(C)  ',
 ' AM(R)',
 ' DMC  ',
 ' D(L)  ',
 ' DMC  ',
 ' D(R)  ',
 ' D(CL)  ',
 ' AM(CLR)  ',
 ' AM(LR)',
 ' D(R)',
 ' D(R)',
 ' FW  ',
 ' GK  ',
 ' D(C)  ',
 ' M(C)  ',
 ' AM(CLR)  ',
 ' DMC  ',
 ' FW  ',
 ' D(C)',
 ' D(L)',
 ' D(CR)  ',
 ' M(C)  ',
 ' D(C)  ',
 ' D(CR)  ',
 ' D(R)',
 ' D(R)  ',
 ' M(C)  ',
 ' D(L)  ',
 ' D(C)',
 ' FW  ',
 ' D(C)',
 ' GK  ',
 ' D(LR)',
 ' D(R)',
 ' AM(CLR)',
 ' D(R)  ',
 ' D(R)',
 ' D(CR)  ',
 ' AM(CLR)',
 ' D(R)',
 ' D(CR)  ',
 ' D(L)',
 ' M(CLR)',
 ' AM(LR)',
 ' AM(CLR)',
 ' D(L)  ',
 ' GK  ',
 ' AM(CR)  ',
 ' AM(CLR)',
 ' GK  ',
 ' D(CR)  ',
 ' D(CL)  ',
 ' D(R)  ',
 ' DMC  ',
 ' DMC  ',
 ' M(CLR)  ',
 ' D(CLR)',
 ' FW  ',
 ' DMC  ',
 ' D(C)  ',
 ' D(C)',
 ' D(C)  ',
 ' M(C)  ',
 ' D(CR)  ',
 ' AM(CL)  ',
 ' D(CL)  ',
 ' D(CR)',
 ' M(CR)  ',
 ' M(C)  ',
 ' DMC  ',
 ' D(C)  ',
 ' FW  ',
 ' M(CL)',
 ' M(CR)  ',
 ' D(CR)  ',
 ' AM(C)  ',
 ' M(CLR)',
 ' AM(CLR)',
 ' D(L)',
 ' AM(CLR)',
 ' AM(L)',
 ' M(CL)  ',
 ' AM(L)',
 ' M(C)  ',
 ' M(CLR)',
 ' D(R)',
 ' M(C)  ',
 ' M(CLR)',
 ' DMC  ',
 ' M(C)  ',
 ' AM(LR)',
 ' FW  ',
 ' FW  ',
 ' M(CLR)',
 ' D(C)  ',
 ' M(CLR)  ',
 ' AM(CLR)  ',
 ' D(R)',
 ' AM(C)',
 ' AM(L)',
 ' AM(R)  ',
 ' FW  ',
 ' FW  ',
 ' AM(R)  ',
 ' DMC  ',
 ' M(C)  ',
 ' FW  ',
 ' DMC',
 ' M(CL)  ',
 ' DMC  ',
 ' AM(L)',
 ' AM(L)',
 ' M(CR)  ',
 ' FW  ',
 ' DMC  ',
 ' FW  ',
 ' AM(R)  ']

In [16]:
# 공백 삭제

for i in range(len(tmp_li)):
    tmp_li[i] = tmp_li[i].replace(' ', '')
tmp_li

['AM(CLR)',
 'FW',
 'FW',
 'AM(L)',
 'AM(CLR)',
 'AM(CL)',
 'FW',
 'D(C)',
 'AM(CLR)',
 'M(C)',
 'AM(CLR)',
 'M(CLR)',
 'M(CL)',
 'FW',
 'D(CR)',
 'AM(R)',
 'AM(LR)',
 'M(C)',
 'DMC',
 'DMC',
 'GK',
 'D(CR)',
 'FW',
 'DMC',
 'AM(CLR)',
 'DMC',
 'D(L)',
 'D(L)',
 'D(CR)',
 'D(CR)',
 'M(C)',
 'AM(CLR)',
 'GK',
 'AM(CR)',
 'AM(CR)',
 'D(C)',
 'AM(CR)',
 'AM(CLR)',
 'D(CR)',
 'AM(LR)',
 'AM(C)',
 'D(CL)',
 'D(LR)',
 'AM(LR)',
 'AM(CR)',
 'D(C)',
 'FW',
 'AM(CLR)',
 'GK',
 'D(L)',
 'AM(R)',
 'M(CLR)',
 'AM(L)',
 'GK',
 'M(C)',
 'GK',
 'AM(CL)',
 'AM(CLR)',
 'GK',
 'M(CR)',
 'D(L)',
 'D(C)',
 'AM(L)',
 'AM(C)',
 'AM(LR)',
 'D(L)',
 'D(R)',
 'AM(CLR)',
 'D(C)',
 'AM(CLR)',
 'D(L)',
 'D(C)',
 'D(R)',
 'AM(L)',
 'D(R)',
 'D(L)',
 'D(LR)',
 'D(LR)',
 'D(CL)',
 'M(C)',
 'D(C)',
 'D(C)',
 'D(C)',
 'AM(R)',
 'D(CL)',
 'M(CL)',
 'DMC',
 'D(LR)',
 'D(C)',
 'D(C)',
 'D(R)',
 'D(C)',
 'D(C)',
 'GK',
 'AM(CLR)',
 'D(L)',
 'M(C)',
 'D(CL)',
 'M(C)',
 'M(CLR)',
 'D(L)',
 'D(C)',
 'M(CLR)',
 'D(C)',
 'AM(LR)',
 'DMC',
 'M(CLR)',
 'GK',
 'AM(R)',
 'M(CLR)',
 'DMC',
 'DMC',
 'D(R)',
 'D(C)',
 'GK',
 'FW',
 'FW',
 'GK',
 'GK',
 'AM(L)',
 'D(L)',
 'D(R)',
 'DMC',
 'D(R)',
 'AM(CLR)',
 'GK',
 'D(C)',
 'D(C)',
 'DMC',
 'AM(CLR)',
 'AM(LR)',
 'D(LR)',
 'GK',
 'D(C)',
 'D(L)',
 'AM(L)',
 'D(C)',
 'M(C)',
 'D(C)',
 'D(R)',
 'D(C)',
 'D(C)',
 'D(C)',
 'AM(LR)',
 'M(LR)',
 'D(CR)',
 'M(CLR)',
 'AM(CLR)',
 'DMC',
 'D(CL)',
 'FW',
 'AM(C)',
 'AM(CL)',
 'DMC',
 'D(C)',
 'D(CLR)',
 'D(C)',
 'D(L)',
 'AM(LR)',
 'AM(CLR)',
 'D(C)',
 'D(CLR)',
 'D(CL)',
 'D(C)',
 'AM(CLR)',
 'AM(CR)',
 'D(C)',
 'AM(LR)',
 'DMC',
 'AM(CL)',
 'AM(LR)',
 'D(C)',
 'DMC',
 'D(CL)',
 'D(C)',
 'M(CLR)',
 'GK',
 'M(C)',
 'D(C)',
 'M(CL)',
 'D(C)',
 'AM(CLR)',
 'M(C)',
 'D(C)',
 'AM(CR)',
 'AM(CLR)',
 'D(L)',
 'D(R)',
 'AM(CLR)',
 'D(CL)',
 'M(C)',
 'FW',
 'DMC',
 'D(C)',
 'M(CLR)',
 'AM(L)',
 'M(C)',
 'AM(L)',
 'D(C)',
 'D(LR)',
 'M(C)',
 'D(R)',
 'FW',
 'D(C)',
 'GK',
 'M(CL)',
 'D(L)',
 'AM(CLR)',
 'D(R)',
 'D(C)',
 'D(C)',
 'D(CL)',
 'D(CLR)',
 'D(C)',
 'DMC',
 'D(C)',
 'D(LR)',
 'D(R)',
 'D(CL)',
 'GK',
 'FW',
 'AM(CLR)',
 'D(L)',
 'AM(CLR)',
 'D(LR)',
 'AM(CLR)',
 'D(C)',
 'AM(R)',
 'DMC',
 'D(L)',
 'DMC',
 'D(R)',
 'D(CL)',
 'AM(CLR)',
 'AM(LR)',
 'D(R)',
 'D(R)',
 'FW',
 'GK',
 'D(C)',
 'M(C)',
 'AM(CLR)',
 'DMC',
 'FW',
 'D(C)',
 'D(L)',
 'D(CR)',
 'M(C)',
 'D(C)',
 'D(CR)',
 'D(R)',
 'D(R)',
 'M(C)',
 'D(L)',
 'D(C)',
 'FW',
 'D(C)',
 'GK',
 'D(LR)',
 'D(R)',
 'AM(CLR)',
 'D(R)',
 'D(R)',
 'D(CR)',
 'AM(CLR)',
 'D(R)',
 'D(CR)',
 'D(L)',
 'M(CLR)',
 'AM(LR)',
 'AM(CLR)',
 'D(L)',
 'GK',
 'AM(CR)',
 'AM(CLR)',
 'GK',
 'D(CR)',
 'D(CL)',
 'D(R)',
 'DMC',
 'DMC',
 'M(CLR)',
 'D(CLR)',
 'FW',
 'DMC',
 'D(C)',
 'D(C)',
 'D(C)',
 'M(C)',
 'D(CR)',
 'AM(CL)',
 'D(CL)',
 'D(CR)',
 'M(CR)',
 'M(C)',
 'DMC',
 'D(C)',
 'FW',
 'M(CL)',
 'M(CR)',
 'D(CR)',
 'AM(C)',
 'M(CLR)',
 'AM(CLR)',
 'D(L)',
 'AM(CLR)',
 'AM(L)',
 'M(CL)',
 'AM(L)',
 'M(C)',
 'M(CLR)',
 'D(R)',
 'M(C)',
 'M(CLR)',
 'DMC',
 'M(C)',
 'AM(LR)',
 'FW',
 'FW',
 'M(CLR)',
 'D(C)',
 'M(CLR)',
 'AM(CLR)',
 'D(R)',
 'AM(C)',
 'AM(L)',
 'AM(R)',
 'FW',
 'FW',
 'AM(R)',
 'DMC',
 'M(C)',
 'FW',
 'DMC',
 'M(CL)',
 'DMC',
 'AM(L)',
 'AM(L)',
 'M(CR)',
 'FW',
 'DMC',
 'FW',
 'AM(R)']

In [17]:
tmp = pd.DataFrame(tmp_li, columns=['position'])
tmp

    position
0    AM(CLR)
1         FW
2         FW
3      AM(L)
4    AM(CLR)
..       ...
338    M(CR)
339       FW
340      DMC
341       FW
342    AM(R)

[343 rows x 1 columns]

In [18]:
# 원래 데이터에 적용

LL_Player_df['position'] = tmp

In [19]:
# 각 포지션이 잘 적용되었는지 확인

LL_Player_df['position'].unique()

array(['AM(CLR)', 'FW', 'AM(L)', 'AM(CL)', 'D(C)', 'M(C)', 'M(CLR)',
       'M(CL)', 'D(CR)', 'AM(R)', 'AM(LR)', 'DMC', 'GK', 'D(L)', 'AM(CR)',
       'AM(C)', 'D(CL)', 'D(LR)', 'M(CR)', 'D(R)', 'M(LR)', 'D(CLR)'],
      dtype=object)

## Apps 전처리

In [20]:
# Apps -> 출전횟수
# 교체 출전의 경우 괄호에 있다.
# 그냥 합쳐준다.
apps_df = LL_Player_df['Apps']
apps_df.head()

0    31(7)
1       24
2    33(1)
3    32(1)
4    25(9)
Name: Apps, dtype: object

In [21]:
tmp_li = apps_df.tolist()
tmp_li

['31(7)',
 '24',
 '33(1)',
 '32(1)',
 '25(9)',
 '22(4)',
 '33(1)',
 '29(4)',
 '16(9)',
 '28(5)',
 '33(3)',
 '29(5)',
 '38',
 '35',
 '22(2)',
 '36(1)',
 '25(11)',
 '25(5)',
 '26(4)',
 '24(9)',
 '34',
 '30(3)',
 '34(1)',
 '28(2)',
 '29(6)',
 '33(1)',
 '31',
 '36(1)',
 '28(1)',
 '26(2)',
 '37',
 '15(16)',
 '31',
 '14(7)',
 '28(6)',
 '16(3)',
 '31(6)',
 '17(2)',
 '21(1)',
 '31(5)',
 '34(3)',
 '22',
 '30(3)',
 '32(4)',
 '27(10)',
 '31',
 '16(10)',
 '17(2)',
 '38',
 '26(9)',
 '28(6)',
 '25(3)',
 '23(13)',
 '21',
 '29(5)',
 '38',
 '30(6)',
 '34(2)',
 '28',
 '14(8)',
 '14(10)',
 '22(1)',
 '34(1)',
 '28(8)',
 '33(5)',
 '16(5)',
 '21(1)',
 '24(6)',
 '34',
 '18(11)',
 '27(2)',
 '27(1)',
 '33',
 '29(6)',
 '25(2)',
 '21(16)',
 '19(4)',
 '34(1)',
 '21(9)',
 '29(6)',
 '31(1)',
 '31(2)',
 '19(1)',
 '26(8)',
 '18(2)',
 '19(11)',
 '31(4)',
 '26(11)',
 '27(1)',
 '23(2)',
 '32(1)',
 '29(2)',
 '35(1)',
 '36',
 '19(11)',
 '35(1)',
 '32(4)',
 '24(2)',
 '31(2)',
 '30(3)',
 '38',
 '22(6)',
 '28(3)',
 '22',
 '16(3)',
 '31(2)',
 '11(8)',
 '38',
 '33(2)',
 '28(5)',
 '35(1)',
 '33',
 '12(11)',
 '19(4)',
 '26',
 '15(6)',
 '22(9)',
 '28',
 '36',
 '18(3)',
 '17(6)',
 '15(11)',
 '27(7)',
 '24(3)',
 '28(5)',
 '28',
 '28',
 '31(3)',
 '28(2)',
 '10(15)',
 '15(11)',
 '32(5)',
 '37',
 '20(3)',
 '20(6)',
 '19(9)',
 '24(1)',
 '19(14)',
 '22(1)',
 '15(8)',
 '28(1)',
 '35',
 '29(2)',
 '21(12)',
 '9(14)',
 '26',
 '28(6)',
 '17(10)',
 '28(8)',
 '31(1)',
 '29(6)',
 '23(8)',
 '25(9)',
 '22(5)',
 '30',
 '18(9)',
 '15(9)',
 '20(3)',
 '15(12)',
 '24(4)',
 '35',
 '16(5)',
 '29(1)',
 '18(2)',
 '26(9)',
 '23(12)',
 '19(6)',
 '24(7)',
 '29(5)',
 '19(16)',
 '23(6)',
 '26(3)',
 '18(8)',
 '21(2)',
 '34',
 '23(9)',
 '22',
 '24(3)',
 '18(7)',
 '21(15)',
 '19(3)',
 '17(8)',
 '28(8)',
 '31',
 '13(12)',
 '19(11)',
 '27(7)',
 '18(4)',
 '29(2)',
 '11(20)',
 '26(3)',
 '17(14)',
 '22(10)',
 '11(10)',
 '27(5)',
 '7(12)',
 '18(6)',
 '12(24)',
 '25(8)',
 '14(6)',
 '13(11)',
 '26(2)',
 '27(11)',
 '28(4)',
 '38',
 '21(10)',
 '22(9)',
 '20(12)',
 '14(6)',
 '33',
 '33(1)',
 '11(13)',
 '26(7)',
 '36',
 '24(10)',
 '24(3)',
 '30(2)',
 '12(13)',
 '15(12)',
 '19',
 '17(13)',
 '25(12)',
 '16(10)',
 '22(11)',
 '21(11)',
 '13(22)',
 '30(1)',
 '33(2)',
 '22(9)',
 '16(6)',
 '33(3)',
 '19(8)',
 '31(1)',
 '19(14)',
 '14(19)',
 '20(10)',
 '11(18)',
 '20(12)',
 '31',
 '18(4)',
 '13(15)',
 '12(12)',
 '18(7)',
 '5(14)',
 '19(6)',
 '16(7)',
 '35',
 '18(16)',
 '20(1)',
 '13(8)',
 '21(11)',
 '15(5)',
 '12(8)',
 '13(12)',
 '20(7)',
 '9(10)',
 '22(3)',
 '37',
 '13(7)',
 '25(12)',
 '11(18)',
 '20(7)',
 '37',
 '18(3)',
 '10(18)',
 '9(17)',
 '26(3)',
 '14(10)',
 '11(8)',
 '20(5)',
 '22(10)',
 '27(2)',
 '26',
 '26(7)',
 '14(9)',
 '19',
 '16(9)',
 '25(3)',
 '31(2)',
 '18(7)',
 '21(9)',
 '21(6)',
 '17(13)',
 '16(10)',
 '20(9)',
 '14(6)',
 '16(12)',
 '16(3)',
 '12(13)',
 '23(1)',
 '16(16)',
 '21(6)',
 '17(11)',
 '12(22)',
 '19(4)',
 '12(20)',
 '17(2)',
 '9(12)',
 '17(11)',
 '9(16)',
 '15(6)',
 '6(13)',
 '6(29)',
 '8(24)',
 '9(15)',
 '9(13)',
 '13(20)',
 '16(12)',
 '14(14)',
 '10(14)',
 '17(17)',
 '7(18)',
 '6(15)',
 '2(20)',
 '24(9)',
 '7(21)',
 '12(16)',
 '14(15)',
 '3(17)',
 '8(15)',
 '19(3)',
 '4(23)',
 '26(9)',
 '10(15)',
 '8(16)',
 '6(13)',
 '7(15)',
 '7(28)',
 '5(20)',
 '13(18)',
 '10(15)',
 '11(15)',
 '6(22)',
 '6(20)',
 '6(15)',
 '4(16)',
 '8(26)',
 '12(18)',
 '11(21)',
 '2(24)',
 '12(16)',
 '3(24)',
 '4(20)']

In [22]:
# ()안에 있는 숫자를 그냥 더해줌
# Apps값을 int형으로 변환

for i in range(343):
    if '(' in tmp_li[i]:
        tmp_li[i] = tmp_li[i].split('(')
        tmp_li[i] = [tmp_li[i][0], tmp_li[i][1].replace(')', '')]
        tmp_li[i] = int(tmp_li[i][0]) + int(tmp_li[i][1])
    else:
        tmp_li[i] = int(tmp_li[i])
    
tmp_df = pd.DataFrame(tmp_li, columns=['Apps'])
tmp_df

     Apps
0      38
1      24
2      34
3      33
4      34
..    ...
338    32
339    26
340    28
341    27
342    24

[343 rows x 1 columns]

In [23]:
LL_Player_df['Apps'] = tmp_df
LL_Player_df[['Apps']]

     Apps
0      38
1      24
2      34
3      33
4      34
..    ...
338    32
339    26
340    28
341    27
342    24

[343 rows x 1 columns]

In [24]:
# 추후 병합을 위해 team_name을 맞춰준다. -> team_table_added값을 기준으로

player_team_df = LL_Player_df['team_name']
player_team_list = player_team_df.to_list()


for i in range(len(player_team_list)): 
    player_team = player_team_list[i]
    
    if player_team == 'Atletico':
        player_team_list[i] = 'Atletico Madrid'
    elif player_team == 'Athletic Bilbao':
        player_team_list[i] = 'Athletic Club'
        

LL_Player_df['team_name'] = pd.DataFrame(player_team_list, columns=['team_name'])
LL_Player_df['team_name'].unique()

array(['Atletico Madrid', 'Real Madrid', 'Barcelona', 'Espanyol',
       'Real Sociedad', 'Mallorca', 'Getafe', 'Villarreal',
       'Rayo Vallecano', 'Girona', 'Cadiz', 'Real Betis', 'Valencia',
       'Celta Vigo', 'Sevilla', 'Almeria', 'Athletic Club', 'Osasuna',
       'Real Valladolid', 'Elche'], dtype=object)

In [25]:
LL_Player_df['team_name'].unique()

array(['Atletico Madrid', 'Real Madrid', 'Barcelona', 'Espanyol',
       'Real Sociedad', 'Mallorca', 'Getafe', 'Villarreal',
       'Rayo Vallecano', 'Girona', 'Cadiz', 'Real Betis', 'Valencia',
       'Celta Vigo', 'Sevilla', 'Almeria', 'Athletic Club', 'Osasuna',
       'Real Valladolid', 'Elche'], dtype=object)

# Team 데이터 가져오기
- team table added

In [26]:
LL_Team_df = pd.read_csv('./Laliga_data/Laliga_22_23_Team_Table_Added.csv')

In [27]:
LL_Team_df.columns

Index(['team_name', 'P', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Goals',
       'Shots pg', 'Yellow', 'Red', 'Poss%', 'Pass%', 'A_Won', 'Rating',
       'Shoted pg', 'Tackles pg', 'Intercept pg', 'Fouls pg', 'Offsides pg',
       'Shots OT pg', 'Dribbles pg', 'Fouled pg'],
      dtype='object')

In [28]:
LL_Team_df['team_name'].unique()

array(['Barcelona', 'Real Madrid', 'Atletico Madrid', 'Real Sociedad',
       'Villarreal', 'Real Betis', 'Osasuna', 'Athletic Club', 'Mallorca',
       'Girona', 'Rayo Vallecano', 'Sevilla', 'Celta Vigo', 'Cadiz',
       'Getafe', 'Valencia', 'Almeria', 'Real Valladolid', 'Espanyol',
       'Elche'], dtype=object)

In [29]:
# team_name이 통일되었는지 확인

for team in LL_Team_df['team_name'].unique().tolist():
    if team not in LL_Player_df['team_name'].unique().tolist():
        print(team)

# 포지션 구분
## 전처리 추가 필요 -> FW, AM, M, DM, D, GK

In [30]:
position_li = LL_Player_df['position'].unique().tolist()
position_li

['AM(CLR)',
 'FW',
 'AM(L)',
 'AM(CL)',
 'D(C)',
 'M(C)',
 'M(CLR)',
 'M(CL)',
 'D(CR)',
 'AM(R)',
 'AM(LR)',
 'DMC',
 'GK',
 'D(L)',
 'AM(CR)',
 'AM(C)',
 'D(CL)',
 'D(LR)',
 'M(CR)',
 'D(R)',
 'M(LR)',
 'D(CLR)']

In [32]:
# 각 포지션별로 데이터 추출

Position_df_li = []

for position in position_li:
    tmp = LL_Player_df[LL_Player_df['position'] == position]
    Position_df_li.append(tmp)

In [33]:
print(position_li[0])
Position_df_li[0]

AM(CLR)

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Disp,UnsTch,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG
0,Antoine Griezmann,63,Atletico Madrid,32,AM(CLR),38,2863,16,2.2,38.3,...,0.9,1.1,1.3,0.6,0.6,0.0,0.8,1.2,0.1,0
4,Rodrygo,52,Real Madrid,22,AM(CLR),34,2382,8,1.4,29.7,...,0.9,1.9,0.5,0.2,0.5,0.0,0.1,0.6,0.0,0
8,Ousmane Dembélé,65,Barcelona,26,AM(CLR),25,1416,7,1.6,29.4,...,0.7,1.1,0.8,0.0,0.6,0.0,0.0,0.4,0.0,0
10,Lee Kang-In,51,Mallorca,22,AM(CLR),36,2841,6,1.5,24.4,...,1.2,1.9,1.2,0.3,1.4,0.0,0.1,1.2,0.1,0
24,Takefusa Kubo,68,Real Sociedad,22,AM(CLR),35,2452,4,1.1,22.5,...,1.2,2.6,1.3,0.3,1.0,0.0,0.1,0.6,0.0,0
31,Marco Asensio,52,Real Madrid,27,AM(CLR),31,1436,6,1.3,22.8,...,0.4,0.6,0.5,0.2,0.3,0.0,0.1,0.4,0.1,0
37,Viktor Tsygankov,2783,Girona,25,AM(CLR),19,1494,6,1.9,29.4,...,0.8,0.8,0.4,0.4,0.4,0.0,0.5,0.7,0.1,0
47,Ayoze Pérez,54,Real Betis,29,AM(CLR),19,1395,1,0.7,19.7,...,1.4,2.1,1.6,0.7,1.7,0.0,0.2,1.6,0.0,0
57,Iñaki Williams,53,Athletic Club,29,AM(CLR),36,2853,3,1.1,19.7,...,1.2,2.0,0.6,0.2,0.9,0.1,0.9,0.4,0.1,0
67,Rodrigo De Paul,63,Atletico Madrid,29,AM(CLR),30,1935,7,1.6,44.9,...,0.5,1.1,1.2,0.3,1.1,0.0,0.1,0.6,0.1,0
69,Adrián Embarba,1799,Almeria,31,AM(CLR),29,1477,3,1.1,14.5,...,1.1,1.7,1.7,0.3,0.8,0.0,0.2,0.8,0.0,0
94,Iker Muniain,53,Athletic Club,30,AM(CLR),30,1692,3,1.6,32.7,...,1.0,1.0,0.7,0.1,0.4,0.0,0.1,0.4,0.0,0
124,Rubén Sobrino,1354,Cadiz,31,AM(CLR),33,2471,2,0.7,18.0,...,1.3,1.7,1.7,0.7,1.5,0.0,0.5,1.0,0.1,0
129,Suso,67,Sevilla,29,AM(CLR),25,1063,4,1.1,19.1,...,0.8,0.7,0.6,0.1,0.5,0.0,0.1,0.5,0.0,0
147,Thomas Lemar,63,Atletico Madrid,27,AM(CLR),27,1259,3,1.0,28.1,...,0.7,0.7,1.1,0.3,0.3,0.0,0.4,0.7,0.1,0
159,Léo Baptistão,1799,Almeria,30,AM(CLR),28,1746,2,0.6,18.3,...,0.6,2.0,1.1,0.7,1.1,0.0,0.3,0.7,0.1,0
164,Dani Rodríguez,51,Mallorca,35,AM(CLR),35,2115,6,0.7,18.5,...,1.1,1.3,1.2,0.6,1.4,0.0,0.3,0.7,0.2,0
181,Samu Castillejo,55,Valencia,28,AM(CLR),25,1371,0,1.2,21.0,...,1.1,1.7,0.8,0.4,1.3,0.0,0.0,1.3,0.1,0
185,Rodri,54,Real Betis,23,AM(CLR),30,1610,3,0.7,26.5,...,0.7,1.2,0.5,0.4,0.2,0.0,0.0,0.3,0.0,0
188,Martin Braithwaite,70,Espanyol,32,AM(CLR),31,2468,2,0.4,13.7,...,0.6,1.7,0.4,0.2,0.6,0.1,0.4,0.3,0.0,0
207,Erik Lamela,67,Sevilla,31,AM(CLR),32,1847,0,0.8,22.6,...,1.6,1.7,1.4,0.2,1.8,0.0,0.1,0.7,0.1,0
221,Javier Puado,70,Espanyol,25,AM(CLR),37,2350,2,0.7,14.7,...,0.8,1.9,0.5,0.3,0.4,0.0,0.3,0.4,0.1,0
223,Óscar Plano,58,Real Valladolid,32,AM(CLR),33,2048,1,0.5,18.5,...,0.7,1.1,1.2,0.9,0.7,0.0,0.5,0.8,0.1,0
225,Ángel Correa,63,Atletico Madrid,28,AM(CLR),35,1449,1,0.7,14.1,...,0.9,1.6,0.3,0.3,0.5,0.0,0.1,0.3,0.0,0
233,Óscar Rodríguez,62,Celta Vigo,24,AM(CLR),33,1772,0,0.7,29.4,...,0.5,0.7,1.0,0.7,0.7,0.0,0.4,0.5,0.1,0
241,Toni Villa,2783,Girona,28,AM(CLR),24,896,3,0.6,12.4,...,0.9,0.8,1.0,0.3,0.5,0.0,0.0,0.5,0.0,0
260,Rubén García,131,Osasuna,29,AM(CLR),29,1152,2,0.9,16.6,...,0.3,0.9,0.7,0.4,0.5,0.0,0.3,0.6,0.0,0
264,Munir El Haddadi,819,Getafe,27,AM(CLR),28,1149,1,0.5,12.4,...,0.9,1.6,0.4,0.3,0.5,0.0,0.1,0.3,0.1,0
270,Pere Milla,833,Elche,30,AM(CLR),32,1875,1,0.4,17.6,...,0.7,1.5,1.0,0.3,0.6,0.0,0.5,0.8,0.1,0
274,Mikel Oyarzabal,68,Real Sociedad,26,AM(CLR),23,1217,1,0.6,15.6,...,0.8,1.2,0.6,0.1,0.7,0.0,0.2,0.6,0.2,0
303,Cristhian Stuani,2783,Girona,36,AM(CLR),32,1078,0,0.3,5.1,...,0.2,0.7,0.4,0.1,1.2,0.0,0.2,0.3,0.0,0
305,Juanmi,54,Real Betis,30,AM(CLR),22,922,0,0.2,10.9,...,0.6,1.0,0.6,0.2,0.7,0.0,0.1,1.1,0.0,0
322,Carles Aleñá,819,Getafe,25,AM(CLR),35,2127,2,0.4,21.7,...,0.7,1.3,0.5,0.1,1.7,0.0,0.4,0.8,0.0,0

In [34]:
# 포지션 압축
# M, FW, AM, D, DMC, M, GK, Forward

tmp_df = LL_Player_df['position']
tmp_li = tmp_df.tolist()
tmp_li

['AM(CLR)',
 'FW',
 'FW',
 'AM(L)',
 'AM(CLR)',
 'AM(CL)',
 'FW',
 'D(C)',
 'AM(CLR)',
 'M(C)',
 'AM(CLR)',
 'M(CLR)',
 'M(CL)',
 'FW',
 'D(CR)',
 'AM(R)',
 'AM(LR)',
 'M(C)',
 'DMC',
 'DMC',
 'GK',
 'D(CR)',
 'FW',
 'DMC',
 'AM(CLR)',
 'DMC',
 'D(L)',
 'D(L)',
 'D(CR)',
 'D(CR)',
 'M(C)',
 'AM(CLR)',
 'GK',
 'AM(CR)',
 'AM(CR)',
 'D(C)',
 'AM(CR)',
 'AM(CLR)',
 'D(CR)',
 'AM(LR)',
 'AM(C)',
 'D(CL)',
 'D(LR)',
 'AM(LR)',
 'AM(CR)',
 'D(C)',
 'FW',
 'AM(CLR)',
 'GK',
 'D(L)',
 'AM(R)',
 'M(CLR)',
 'AM(L)',
 'GK',
 'M(C)',
 'GK',
 'AM(CL)',
 'AM(CLR)',
 'GK',
 'M(CR)',
 'D(L)',
 'D(C)',
 'AM(L)',
 'AM(C)',
 'AM(LR)',
 'D(L)',
 'D(R)',
 'AM(CLR)',
 'D(C)',
 'AM(CLR)',
 'D(L)',
 'D(C)',
 'D(R)',
 'AM(L)',
 'D(R)',
 'D(L)',
 'D(LR)',
 'D(LR)',
 'D(CL)',
 'M(C)',
 'D(C)',
 'D(C)',
 'D(C)',
 'AM(R)',
 'D(CL)',
 'M(CL)',
 'DMC',
 'D(LR)',
 'D(C)',
 'D(C)',
 'D(R)',
 'D(C)',
 'D(C)',
 'GK',
 'AM(CLR)',
 'D(L)',
 'M(C)',
 'D(CL)',
 'M(C)',
 'M(CLR)',
 'D(L)',
 'D(C)',
 'M(CLR)',
 'D(C)',
 'AM(LR)',
 'DMC',
 'M(CLR)',
 'GK',
 'AM(R)',
 'M(CLR)',
 'DMC',
 'DMC',
 'D(R)',
 'D(C)',
 'GK',
 'FW',
 'FW',
 'GK',
 'GK',
 'AM(L)',
 'D(L)',
 'D(R)',
 'DMC',
 'D(R)',
 'AM(CLR)',
 'GK',
 'D(C)',
 'D(C)',
 'DMC',
 'AM(CLR)',
 'AM(LR)',
 'D(LR)',
 'GK',
 'D(C)',
 'D(L)',
 'AM(L)',
 'D(C)',
 'M(C)',
 'D(C)',
 'D(R)',
 'D(C)',
 'D(C)',
 'D(C)',
 'AM(LR)',
 'M(LR)',
 'D(CR)',
 'M(CLR)',
 'AM(CLR)',
 'DMC',
 'D(CL)',
 'FW',
 'AM(C)',
 'AM(CL)',
 'DMC',
 'D(C)',
 'D(CLR)',
 'D(C)',
 'D(L)',
 'AM(LR)',
 'AM(CLR)',
 'D(C)',
 'D(CLR)',
 'D(CL)',
 'D(C)',
 'AM(CLR)',
 'AM(CR)',
 'D(C)',
 'AM(LR)',
 'DMC',
 'AM(CL)',
 'AM(LR)',
 'D(C)',
 'DMC',
 'D(CL)',
 'D(C)',
 'M(CLR)',
 'GK',
 'M(C)',
 'D(C)',
 'M(CL)',
 'D(C)',
 'AM(CLR)',
 'M(C)',
 'D(C)',
 'AM(CR)',
 'AM(CLR)',
 'D(L)',
 'D(R)',
 'AM(CLR)',
 'D(CL)',
 'M(C)',
 'FW',
 'DMC',
 'D(C)',
 'M(CLR)',
 'AM(L)',
 'M(C)',
 'AM(L)',
 'D(C)',
 'D(LR)',
 'M(C)',
 'D(R)',
 'FW',
 'D(C)',
 'GK',
 'M(CL)',
 'D(L)',
 'AM(CLR)',
 'D(R)',
 'D(C)',
 'D(C)',
 'D(CL)',
 'D(CLR)',
 'D(C)',
 'DMC',
 'D(C)',
 'D(LR)',
 'D(R)',
 'D(CL)',
 'GK',
 'FW',
 'AM(CLR)',
 'D(L)',
 'AM(CLR)',
 'D(LR)',
 'AM(CLR)',
 'D(C)',
 'AM(R)',
 'DMC',
 'D(L)',
 'DMC',
 'D(R)',
 'D(CL)',
 'AM(CLR)',
 'AM(LR)',
 'D(R)',
 'D(R)',
 'FW',
 'GK',
 'D(C)',
 'M(C)',
 'AM(CLR)',
 'DMC',
 'FW',
 'D(C)',
 'D(L)',
 'D(CR)',
 'M(C)',
 'D(C)',
 'D(CR)',
 'D(R)',
 'D(R)',
 'M(C)',
 'D(L)',
 'D(C)',
 'FW',
 'D(C)',
 'GK',
 'D(LR)',
 'D(R)',
 'AM(CLR)',
 'D(R)',
 'D(R)',
 'D(CR)',
 'AM(CLR)',
 'D(R)',
 'D(CR)',
 'D(L)',
 'M(CLR)',
 'AM(LR)',
 'AM(CLR)',
 'D(L)',
 'GK',
 'AM(CR)',
 'AM(CLR)',
 'GK',
 'D(CR)',
 'D(CL)',
 'D(R)',
 'DMC',
 'DMC',
 'M(CLR)',
 'D(CLR)',
 'FW',
 'DMC',
 'D(C)',
 'D(C)',
 'D(C)',
 'M(C)',
 'D(CR)',
 'AM(CL)',
 'D(CL)',
 'D(CR)',
 'M(CR)',
 'M(C)',
 'DMC',
 'D(C)',
 'FW',
 'M(CL)',
 'M(CR)',
 'D(CR)',
 'AM(C)',
 'M(CLR)',
 'AM(CLR)',
 'D(L)',
 'AM(CLR)',
 'AM(L)',
 'M(CL)',
 'AM(L)',
 'M(C)',
 'M(CLR)',
 'D(R)',
 'M(C)',
 'M(CLR)',
 'DMC',
 'M(C)',
 'AM(LR)',
 'FW',
 'FW',
 'M(CLR)',
 'D(C)',
 'M(CLR)',
 'AM(CLR)',
 'D(R)',
 'AM(C)',
 'AM(L)',
 'AM(R)',
 'FW',
 'FW',
 'AM(R)',
 'DMC',
 'M(C)',
 'FW',
 'DMC',
 'M(CL)',
 'DMC',
 'AM(L)',
 'AM(L)',
 'M(CR)',
 'FW',
 'DMC',
 'FW',
 'AM(R)']

In [35]:
# 포지션 압축

for i in range(len(tmp_li)):
    pos_tmp = tmp_li[i]
    if '(' in pos_tmp:
        pos_tmp_li = pos_tmp.split('(')
        tmp_li[i] = pos_tmp_li[0]
    
    if tmp_li[i] == 'Forward':
        tmp_li[i] = 'FW'
        
    elif tmp_li[i] == 'DMC':
        tmp_li[i] = 'DM'
        
    elif tmp_li[i] == 'Midfielder':
        tmp_li[i] = 'M'

In [36]:
# 원본 데이터에 적용

LL_Player_df['position'] = pd.DataFrame(tmp_li, columns=['position'])

In [37]:
# 적용되었는지 확인

LL_Player_df['position'].unique()

array(['AM', 'FW', 'D', 'M', 'DM', 'GK'], dtype=object)

# 포지션별 dataframe 생성
- csv파일도 생성

In [39]:
FW_player_df = LL_Player_df[LL_Player_df['position'] == 'FW']
print(FW_player_df.shape)
#FW_player_df.to_csv('LL_FW_Player.csv', encoding='utf-8-sig')

(24, 34)

In [45]:
AM_player_df = LL_Player_df[LL_Player_df['position'] == 'AM']
AM_player_df.shape
#AM_player_df.to_csv('LL_AM_Player.csv', encoding='utf-8-sig')

(84, 34)

In [46]:
M_player_df = LL_Player_df[LL_Player_df['position'] == 'M']
M_player_df.shape
#M_player_df.to_csv('LL_M_Player.csv', encoding='utf-8-sig')

(50, 34)

In [47]:
DM_player_df = LL_Player_df[LL_Player_df['position'] == 'DM']
DM_player_df.shape
#DM_player_df.to_csv('LL_DM_Player.csv', encoding='utf-8-sig')

(28, 34)

In [48]:
D_player_df = LL_Player_df[LL_Player_df['position'] == 'D']
D_player_df.shape
#D_player_df.to_csv('LL_D_Player.csv', encoding='utf-8-sig')

(137, 34)

In [49]:
GK_player_df = LL_Player_df[LL_Player_df['position'] == 'GK']
GK_player_df.shape
#GK_player_df.to_csv('LL_GK_Player.csv', encoding='utf-8-sig')

(20, 34)

343