In [1]:
import pandas as pd
import os

In [2]:
bl_player = pd.read_csv('./Budesliga_data/Bundesliga_Player_22_23.csv')
bl_player.drop('Unnamed: 0', axis=1, inplace=True)
bl_player

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Disp,UnsTch,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG
0,Jude Bellingham,44,Borussia Dortmund,19,M(CLR),30(1),2693,4,1.1,51.2,...,1.9,2.0,2.5,1.1,1.3,0.0,0.9,0.5,0.1,0
1,Joshua Kimmich,37,Bayern,28,"D(CR),DMC,M(R)",32(1),2815,6,2.6,75.5,...,0.8,0.8,2.4,1.2,0.7,0.0,1.1,1.0,0.2,0
2,Niclas Füllkrug,42,Werder Bremen,30,FW,28,2479,5,1.2,32.3,...,1.8,2.6,0.3,0.0,1.2,0.0,0.9,0.4,0.1,0
3,Christopher Nkunku,7614,RBL,25,"M(CLR),FW",20(5),1899,4,1.6,23.8,...,1.5,1.8,0.2,0.3,0.7,0.0,0.4,0.2,0.1,0
4,Jamal Musiala,37,Bayern,20,M(CL),26(7),2212,10,1.6,30.0,...,2.1,2.4,1.0,0.6,0.7,0.0,0.1,0.7,0.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,Lucas Alario,45,Eintracht Frankfurt,30,FW,2(18),317,0,0.1,4.3,...,0.4,0.2,0.2,0.1,0.5,0.0,0.6,0.1,0.0,0
282,Luca Pfeiffer,41,Stuttgart,26,FW,6(13),692,0,0.6,10.5,...,0.3,0.7,0.1,0.1,0.7,0.0,0.3,0.1,0.0,0
283,Danny Latza,39,Schalke,33,M(C),8(12),845,1,0.2,18.6,...,0.4,0.4,0.9,0.3,0.7,0.1,0.7,0.6,0.1,0
284,Nils Petersen,50,Freiburg,34,FW,0(27),257,0,0.0,2.7,...,0.1,0.6,0.2,0.0,0.2,0.0,0.2,0.1,0.1,0
285,Patrick Herrmann,134,Borussia M.Gladbach,32,"M(LR),FW",0(21),151,0,0.2,4.4,...,0.2,0.0,0.3,0.1,0.2,0.0,0.0,0.1,0.0,0

In [19]:
player_list = bl_player['player_name'].unique().tolist()

In [3]:
bl_path_list = os.listdir('./Budesliga_data/Player_Value/')
print(len(bl_path_list))
merged_li = []

for path in bl_path_list:
    tmp = pd.read_csv('./Budesliga_data/Player_Value/'+path)
    tmp.columns = ['player_name', 'Position', 'Date of Birth', 'Age', 'Nationality', 'Market Value']
    merged_li.append(pd.merge(bl_player, tmp, on='player_name', how='inner'))

18

In [4]:
len(merged_li)

18

In [5]:
bl_merged = pd.concat([merged_li[0], merged_li[5], merged_li[10], merged_li[14],
                       merged_li[1], merged_li[6], merged_li[11], merged_li[15],
                       merged_li[2], merged_li[7], merged_li[12], merged_li[16],
                       merged_li[3], merged_li[8], merged_li[13], merged_li[17],
                       merged_li[4], merged_li[9]], ignore_index=True)

In [6]:
bl_merged

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Offsides,Clear,Drb,Blocks,OwnG,Position,Date of Birth,Age,Nationality,Market Value
0,Christopher Nkunku,7614,RBL,25,"M(CLR),FW",20(5),1899,4,1.6,23.8,...,0.0,0.4,0.2,0.1,0,Attacking Midfield,"Nov 14, 1997",25,France,€80.00m
1,Dominik Szoboszlai,7614,RBL,22,AM(CLR),28(3),2453,8,2.3,45.2,...,0.0,0.7,0.8,0.1,0,Central Midfield,"Oct 25, 2000",22,Hungary,€50.00m
2,Willi Orbán,7614,RBL,30,D(C),33,2951,0,0.2,79.6,...,0.5,3.9,0.5,0.7,1,Centre-Back,"Nov 3, 1992",30,Hungary,€10.00m
3,Dani Olmo,7614,RBL,25,"AM(CLR),FW",15(8),1285,5,1.7,25.0,...,0.0,0.2,0.3,0.0,0,Attacking Midfield,"May 7, 1998",25,Spain,€40.00m
4,Konrad Laimer,7614,RBL,26,"D(R),M(CR)",17(4),1474,0,0.8,34.6,...,0.0,0.3,1.1,0.2,0,Central Midfield,"May 27, 1997",26,Austria,€28.00m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,Anthony Modeste,44,Borussia Dortmund,35,FW,7(12),807,1,0.4,6.4,...,0.0,1.1,0.2,0.0,0,Centre-Forward,"Apr 14, 1988",35,France,€700k
271,Marvin Schwäbe,282,FC Koln,28,GK,34,3060,0,0.0,37.4,...,0.0,0.4,0.0,0.0,0,Goalkeeper,"Apr 25, 1995",28,Germany,€7.00m
272,Denis Huseinbasic,282,FC Koln,21,AM(C),7(17),782,1,0.2,11.2,...,0.0,0.2,0.6,0.1,0,Central Midfield,"Jul 3, 2001",21,Bosnia-Herzegovina,€5.00m
273,Kingsley Schindler,282,FC Koln,29,"D(R),M(R),FW",8(21),1072,1,0.3,13.8,...,0.0,0.8,0.3,0.1,0,Right-Back,"Jul 12, 1993",29,Ghana,€1.00m
274,Sargis Adamyan,282,FC Koln,30,"AM(CLR),FW",4(20),634,2,0.3,6.6,...,0.0,0.2,0.4,0.0,0,Centre-Forward,"May 23, 1993",30,Armenia,€1.00m

In [7]:
epl_player = pd.read_csv('./EPL_data/PL_Player_22_23.csv')
epl_player.drop('Unnamed: 0', axis=1, inplace=True)

epl_path_list = os.listdir('./EPL_data/Player_values/')
epl_path_list.pop(3)
merged_li = []

for path in epl_path_list:
    tmp = pd.read_csv('./EPL_data/Player_values/'+path)
    tmp.columns = ['player_name', 'Position', 'Date of Birth', 'Age', 'Nationality', 'Market Value']
    merged_li.append(pd.merge(epl_player, tmp, on='player_name', how='inner'))
    
epl_merged = pd.concat([merged_li[0], merged_li[5], merged_li[10], merged_li[14],
                       merged_li[1], merged_li[6], merged_li[11], merged_li[15],
                       merged_li[2], merged_li[7], merged_li[12], merged_li[16],
                       merged_li[3], merged_li[8], merged_li[13], merged_li[17],
                       merged_li[4], merged_li[9], merged_li[18], merged_li[19],], ignore_index=True)

In [8]:
epl_player

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Disp,UnsTch,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG
0,Kevin De Bruyne,167,Man City,31,"M(CLR),FW",28(4),2425,16,3.1,42.4,...,0.9,1.3,0.9,0.3,0.6,0.0,0.3,0.8,0.1,0
1,Erling Haaland,167,Man City,22,FW,33(2),2779,8,0.9,13.7,...,0.7,1.5,0.1,0.1,0.9,0.0,0.4,0.1,0.1,0
2,Harry Kane,30,Tottenham,29,"AM(C),FW",38,3408,3,1.5,22.4,...,1.5,1.9,0.4,0.1,0.8,0.1,0.5,0.4,0.2,0
3,Bruno Fernandes,32,Man Utd,28,M(CLR),37,3320,8,3.2,50.1,...,1.1,1.1,1.8,0.7,1.1,0.0,1.0,1.1,0.1,0
4,Gabriel Jesus,13,Arsenal,26,"AM(LR),FW",24(2),2075,6,1.2,25.9,...,2.5,3.4,1.3,0.4,1.7,0.0,0.5,0.7,0.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,Dennis Praet,14,Leicester,29,AM(CR),6(16),641,0,0.1,11.3,...,0.5,0.5,0.5,0.2,0.4,0.0,0.2,0.2,0.1,0
304,Jean-Philippe Mateta,162,Crystal Palace,25,FW,6(23),754,0,0.2,5.0,...,0.6,0.9,0.2,0.1,0.6,0.0,0.6,0.1,0.0,0
305,Flynn Downes,29,West Ham,24,M(C),7(14),758,0,0.1,15.6,...,0.3,0.5,0.8,0.3,0.4,0.0,0.2,0.3,0.1,0
306,Tom Davies,31,Everton,24,M(C),4(15),530,0,0.1,12.1,...,0.2,0.9,0.8,0.2,0.5,0.0,0.4,0.4,0.1,0
307,Sam Surridge,174,Nottingham Forest,24,FW,1(19),308,0,0.1,3.9,...,0.2,0.7,0.3,0.0,0.6,0.0,0.4,0.2,0.1,0

In [9]:
epl_merged

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Offsides,Clear,Drb,Blocks,OwnG,Position,Date of Birth,Age,Nationality,Market Value
0,James Ward-Prowse,18,Southampton,28,M(CR),38,3373,4,1.9,50.5,...,0.0,1.2,1.1,0.3,1,Central Midfield,NaN,28,England,€38.00m
1,Mohammed Salisu,18,Southampton,24,D(CL),21(1),1973,1,0.3,49.5,...,0.5,5.4,0.5,1.1,1,Centre-Back,NaN,24,Ghana,€18.00m
2,Armel Bella-Kotchap,18,Southampton,21,D(C),24,1885,2,0.3,38.6,...,0.3,4.5,0.2,0.5,0,Centre-Back,NaN,21,Germany,€20.00m
3,Jan Bednarek,18,Southampton,27,D(C),20,1674,0,0.2,44.4,...,0.4,4.4,0.2,1.4,1,Centre-Back,NaN,27,Poland,€14.00m
4,Ché Adams,18,Southampton,26,"AM(CL),FW",23(5),1998,3,0.9,17.2,...,0.1,0.8,0.2,0.1,0,Centre-Forward,NaN,26,Scotland,€20.00m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,Danny Ward,14,Leicester,30,GK,26,2340,0,0.0,30.2,...,0.0,0.7,0.1,0.0,0,Goalkeeper,NaN,30,Wales,€6.00m
300,Patson Daka,14,Leicester,24,FW,13(17),1181,4,0.6,9.2,...,0.0,0.2,0.3,0.1,0,Centre-Forward,NaN,24,Zambia,€18.00m
301,Jamie Vardy,14,Leicester,36,"AM(L),FW",19(18),1855,4,0.4,6.9,...,0.0,0.8,0.2,0.1,0,Centre-Forward,NaN,36,England,€2.50m
302,Nampalys Mendy,14,Leicester,31,M(C),7(12),751,0,0.1,21.5,...,0.1,0.1,0.4,0.2,0,Defensive Midfield,NaN,31,Senegal,€2.50m
303,Dennis Praet,14,Leicester,29,AM(CR),6(16),641,0,0.1,11.3,...,0.0,0.2,0.2,0.1,0,Central Midfield,NaN,29,Belgium,€7.00m

In [10]:
ll_player = pd.read_csv('./Laliga_data/Laliga_Player_22_23.csv')
ll_player.drop('Unnamed: 0', axis=1, inplace=True)

ll_path_list = os.listdir('./Laliga_data/Team_player_values/')
ll_path_list.pop(2)
ll_path_list.pop(6)
merged_li = []

for path in ll_path_list:
    tmp = pd.read_csv('./Laliga_data/Team_player_values/'+path)
    tmp.columns = ['player_name', 'Position', 'Date of Birth', 'Age', 'Nationality', 'Market Value']
    merged_li.append(pd.merge(ll_player, tmp, on='player_name', how='inner'))
    
ll_merged = pd.concat([merged_li[0], merged_li[5], merged_li[10], merged_li[14],
                       merged_li[1], merged_li[6], merged_li[11], merged_li[15],
                       merged_li[2], merged_li[7], merged_li[12], merged_li[16],
                       merged_li[3], merged_li[8], merged_li[13], merged_li[17],
                       merged_li[4], merged_li[9], merged_li[18], merged_li[19],], ignore_index=True)

In [11]:
ll_player

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Disp,UnsTch,Tackles,Inter,Fouls,Offsides,Clear,Drb,Blocks,OwnG
0,Antoine Griezmann,63,Atletico,32,"AM(CLR),FW",31(7),2863,16,2.2,38.3,...,0.9,1.1,1.3,0.6,0.6,0.0,0.8,1.2,0.1,0
1,Karim Benzema,52,Real Madrid,35,FW,24,2044,3,2.0,44.0,...,1.2,1.3,0.4,0.1,0.4,0.0,0.2,0.4,0.0,0
2,Robert Lewandowski,65,Barcelona,34,FW,33(1),2852,7,1.1,22.4,...,1.5,2.8,0.5,0.1,1.1,0.1,0.4,0.2,0.0,0
3,Vinícius Júnior,52,Real Madrid,22,"AM(L),FW",32(1),2833,9,1.9,32.1,...,1.8,3.1,0.9,0.2,1.4,0.0,0.0,0.8,0.0,0
4,Rodrygo,52,Real Madrid,22,"AM(CLR),FW",25(9),2382,8,1.4,29.7,...,0.9,1.9,0.5,0.2,0.5,0.0,0.1,0.6,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,Antonio Sánchez,51,Mallorca,26,M(CR),11(21),1066,0,0.2,12.2,...,0.6,0.8,0.6,0.7,0.8,0.0,0.2,0.8,0.0,0
339,Abdón Prats,51,Mallorca,30,FW,2(24),398,1,0.3,3.5,...,0.5,0.3,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0
340,Raúl Guti,833,Elche,26,DMC,12(16),1084,0,0.1,14.2,...,0.6,0.5,0.6,0.3,0.3,0.0,0.2,0.4,0.1,0
341,Radamel Falcao,64,Rayo Vallecano,37,FW,3(24),598,0,0.1,6.1,...,0.3,1.1,0.1,0.1,0.6,0.0,0.4,0.3,0.0,0
342,Salvi Sánchez,64,Rayo Vallecano,32,AM(R),4(20),475,0,0.3,6.3,...,0.3,0.4,0.5,0.1,0.3,0.0,0.0,0.3,0.0,0

In [12]:
ll_merged[ll_merged['player_name'] == 'Antoine Griezmann']

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Offsides,Clear,Drb,Blocks,OwnG,Position,Date of Birth,Age,Nationality,Market Value
303,Antoine Griezmann,63,Atletico,32,"AM(CLR),FW",31(7),2863,16,2.2,38.3,...,0.0,0.8,1.2,0.1,0,Centre-Forward,"Mar 21, 1991",32,France,€25.00m

In [13]:
l1_player = pd.read_csv('./League1_data/Ligue1_Player_22_23.csv')
l1_player.drop('Unnamed: 0', axis=1, inplace=True)

l1_path_list = os.listdir('./League1_data/Team_player_values/')
l1_path_list.pop(3)
merged_li = []

for path in l1_path_list:
    tmp = pd.read_csv('./League1_data/Team_player_values/'+path)
    tmp.columns = ['player_name', 'Position', 'Date of Birth', 'Age', 'Nationality', 'Market Value']
    merged_li.append(pd.merge(l1_player, tmp, on='player_name', how='inner'))
    
l1_merged = pd.concat([merged_li[0], merged_li[5], merged_li[10], merged_li[14],
                       merged_li[1], merged_li[6], merged_li[11], merged_li[15],
                       merged_li[2], merged_li[7], merged_li[12], merged_li[16],
                       merged_li[3], merged_li[8], merged_li[13], merged_li[17],
                       merged_li[4], merged_li[9], merged_li[18], merged_li[19],], ignore_index=True)

In [14]:
l1_merged

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Offsides,Clear,Drb,Blocks,OwnG,Position,Date of Birth,Age,Nationality,Market Value
0,Florian Sotoca,309,Lens,32,"M(CR),FW",34(4),3064,9,1.6,36.6,...,0.0,1.3,0.7,0.1,0,Centre-Forward,"Oct 25, 1990",32,France,€4.00m
1,Seko Fofana,309,Lens,28,M(C),34(1),3079,5,1.0,50.3,...,0.0,0.4,0.7,0.1,0,Central Midfield,"May 7, 1995",28,Cote d'Ivoire,€32.00m
2,Przemyslaw Frankowski,309,Lens,28,"D(R),M(CLR)",31(6),2838,3,1.8,36.1,...,0.1,0.9,1.1,0.2,0,Right Midfield,"Apr 12, 1995",28,Poland,€9.00m
3,Loïs Openda,309,Lens,23,FW,29(9),2529,4,0.6,10.6,...,0.0,0.2,0.3,0.0,0,Centre-Forward,"Feb 16, 2000",23,Belgium,€35.00m
4,Jonathan Gradit,309,Lens,30,D(CR),33,2830,3,0.4,62.5,...,0.3,2.5,0.7,0.8,0,Centre-Back,"Nov 24, 1992",30,France,€5.00m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,Adil Rami,229,Troyes,37,D(C),18(2),1600,1,0.2,35.9,...,0.2,3.7,0.8,0.8,0,Centre-Back,"Dec 27, 1985",37,France,€250k
311,Thierno Baldé,229,Troyes,21,"D(R),M(R)",25(6),2161,1,0.6,23.8,...,0.2,1.2,0.4,0.1,0,Right-Back,"Jun 10, 2002",21,France,€4.00m
312,Erik Palmer-Brown,229,Troyes,26,D(C),36(2),3194,0,0.2,37.5,...,0.5,4.1,0.4,0.8,1,Centre-Back,"Apr 24, 1997",26,United States,€2.50m
313,Andreas Bruus,229,Troyes,24,"D(R),M(R)",18(9),1626,2,0.8,17.4,...,0.0,0.8,0.4,0.1,0,Right-Back,"Jan 16, 1999",24,Denmark,€2.00m
314,Iké Ugbo,229,Troyes,24,FW,9(16),889,1,0.1,5.4,...,0.0,0.2,0.3,0.1,0,Centre-Forward,"Sep 21, 1998",24,Canada,€3.00m

In [15]:
sa_player = pd.read_csv('./SerieA_data/Serie_Player_22_23.csv')
sa_player.drop('Unnamed: 0', axis=1, inplace=True)

sa_path_list = os.listdir('./SerieA_data/Team_player_values/')
sa_path_list.pop(2)
merged_li = []

for path in sa_path_list:
    tmp = pd.read_csv('./SerieA_data/Team_player_values/'+path)
    tmp.columns = ['player_name', 'Position', 'Date of Birth', 'Age', 'Nationality', 'Market Value']
    merged_li.append(pd.merge(sa_player, tmp, on='player_name', how='inner'))
    
sa_merged = pd.concat([merged_li[0], merged_li[5], merged_li[10], merged_li[14],
                       merged_li[1], merged_li[6], merged_li[11], merged_li[15],
                       merged_li[2], merged_li[7], merged_li[12], merged_li[16],
                       merged_li[3], merged_li[8], merged_li[13], merged_li[17],
                       merged_li[4], merged_li[9], merged_li[18], merged_li[19],], ignore_index=True)

In [16]:
sa_merged

,player_name,team_number,team_name,age,position,Apps,Mins,Assists,KeyP,AvgP,...,Offsides,Clear,Drb,Blocks,OwnG,Position,Date of Birth,Age,Nationality,Market Value
0,Lautaro Martínez,75,Inter,25,FW,27(11),2577,6,1.2,17.3,...,0.0,0.4,0.4,0.0,0,Centre-Forward,"Aug 22, 1997",25,Argentina,€85.00m
1,Romelu Lukaku,75,Inter,30,"AM(R),FW",19(6),1663,6,1.3,15.1,...,0.0,0.6,0.1,0.0,0,Centre-Forward,"May 13, 1993",30,Belgium,€40.00m
2,Nicolò Barella,75,Inter,26,AM(C),31(4),2622,6,1.6,42.9,...,0.0,0.3,0.7,0.1,0,Central Midfield,"Feb 7, 1997",26,Italy,€75.00m
3,Federico Dimarco,75,Inter,25,"D(CL),M(L)",26(7),2089,3,1.8,28.2,...,0.0,0.4,0.3,0.1,0,Left-Back,"Nov 10, 1997",25,Italy,€35.00m
4,Stefan de Vrij,75,Inter,31,D(C),22(5),1944,0,0.0,44.5,...,0.3,2.9,0.2,0.4,0,Centre-Back,"Feb 5, 1992",31,Netherlands,€8.00m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,Assan Ceesay,79,Lecce,29,FW,20(14),1818,0,0.2,10.9,...,0.0,0.6,0.2,0.1,0,Centre-Forward,"Mar 17, 1994",29,The Gambia,€2.50m
301,Federico Di Francesco,79,Lecce,29,"M(LR),FW",23(13),2040,2,0.7,12.6,...,0.0,0.4,0.3,0.0,0,Left Winger,"Jun 14, 1994",29,Italy,€1.80m
302,Lameck Banda,79,Lecce,22,AM(L),19(17),1637,1,0.4,10.3,...,0.0,0.1,0.7,0.1,0,Left Winger,"Jan 29, 2001",22,Zambia,€4.00m
303,Lorenzo Colombo,79,Lecce,21,FW,18(15),1518,2,0.5,9.6,...,0.0,0.2,0.2,0.0,0,Centre-Forward,"Mar 8, 2002",21,Italy,€5.00m
304,Kristoffer Askildsen,79,Lecce,22,M(C),7(14),724,0,0.3,11.6,...,0.0,0.3,0.3,0.2,0,Central Midfield,"Jan 9, 2001",22,Norway,€2.00m

In [17]:
#bl_merged.to_csv('BL_player_value_merged.csv')
#epl_merged.to_csv('EPL_player_value_merged.csv')
#ll_merged.to_csv('LL_player_value_merged.csv')
#l1_merged.to_csv('L1_player_value_merged.csv')
#sa_merged.to_csv('SA_player_value_merged.csv')